### ISSUE TITLE
Suggest a new logo for our Crop-Ai organization

### ISSUE THREAD

**Issue by rajats98** [CropAi/Frontend#1]
# Suggest a new logo for our Crop-Ai organization

**This is an open Issue** - This issue will not be assigned, anyone can work on this

### Guidelines
1. Profile picture should be a PNG, JPG, or GIF file under 1 MB in size. For the best quality rendering, we recommend keeping the image at 500 by 500 pixels.
1. Explain your design.
1. Mention How is it better than the earlier one(if any selected)
1. Background should be transparent (as we need to place it over colored graphics in website)

**Any PR not satisfying guidelines will be ignored**
_Add your logo to /design/logo-designs/submitted-logos_
### Suggestion
1. Magnifying glass(for detection), plant can add more relevance to logo
1. One can use logo makers, eg. https://brandmark.io/ (we just have to give keywords and AI will be used to generate logo for us) 
 
**_ISSUE TO CLOSE ON 05/04/2020_**

**Comment by abhu-A-J** [comment]
@rajats98 Can I work on this??

**Comment by annu12340** [comment]
I would like to work on this. Please assign it to me

**Comment by rajats98** [comment]
@annu12340 
Go for it, Make a PR... this issue is open and you can submit PR without assignment. :) 
Just read the guidelines carefully.
Also, give a tentative date/time of submission.

**Comment by annu12340** [comment]
ok thanks :)

**Comment by Sulekhiya** [comment]
Hello @annu12340  Please give tentative time of submission

**Comment by annu12340** [comment]
I would do it by tommorrow

**Comment by goyalmuskan** [comment]
@rajats98 Can we still work on this issue?

**Comment by rajats98** [comment]
> @rajats98 Can we still work on this issue?

yes, but submit your logo by tomorrow.

**Comment by Satyam3976** [comment]
@rajats98 I am also working on this issue, will submit the PR in the evening.
