### ISSUE TITLE
delete lib folder

### ISSUE THREAD

**Issue by rajats98** [CropAi/Frontend#100]
Delete the lib folder (present inside src folder)

**Comment by Adyasha8105** [comment]
Can I take this issue?

**Comment by abhishekgupta368** [comment]
I can do it.

**Comment by annu12340** [comment]
Can I take this issue?

**Comment by Sapna2001** [comment]
Please assign me this issue.

**Comment by rajats98** [comment]
@annu12340 assigning this to you!
