### ISSUE TITLE
Make landing2.html responsive

### ISSUE THREAD

**Issue by rajats98** [CropAi/Frontend#101]
src/landing pages/landing-page-2/landing2.html

Update bootstrap to latest version (4.4.1)
Try to use bootstrap extensively to design, position(spacing and size etc.) elements,
**make the page responsive**
some alteration in the design are allowed but it should look good
remove/update the redundant CSS on the go.

If there is any doubt, Kindly ask.
Code neatly, Comment nicely!!

**Comment by abhishekgupta368** [comment]
I can do it. Can you Assign me, Please?

**Comment by shwetagurnani** [comment]
pls assign me this issue

**Comment by Adyasha8105** [comment]
Can I take this issue?

**Comment by annu12340** [comment]
Can I take this issue?

**Comment by Satyam3976** [comment]
Can I

**Comment by rajats98** [comment]
@abhishekgupta368 assigned you another issue, as you told you are a beginner in frontend.

**Comment by rajats98** [comment]
@Adyasha8105 assigning this to you.
In case you are not comfortable with Bootstrap 4, inform!

**Comment by Adyasha8105** [comment]
> @Adyasha8105 assigning this to you.
> In case you are not comfortable with Bootstrap 4, inform!

No, first I will try.
