### ISSUE TITLE
Fetching user details

### ISSUE THREAD

**Issue by rajats98** [CropAi/Frontend#102]
Create a folder **contributors page** (exactly same) inside src 
Create a js script named script_for_fetching_userdata.js (or similar name)

Add GitHub username of contributors to an array ( say, contributor_usernames)
get contributors from each of the 4 repository present in github.com/CropAi

get details for all users from https://api.github.com/users/{username}, and store only following keys 
```
login
avatar
html_url
name
bio
```
for each user in  contributor_usernames array.

If there is any doubt, Kindly ask.
Code neatly, Comment nicely!!

**Comment by abhu-A-J** [comment]
@rajats98 Sir May I ??

**Comment by shwetagurnani** [comment]
pls assign me this issue

**Comment by abhishekgupta368** [comment]
I can do it. Can you assign me ?

**Comment by Satyam3976** [comment]
Can I

**Comment by annu12340** [comment]
can i work on this issue

**Comment by rajats98** [comment]
@shwetagurnani Assigning this to you

**Comment by rajats98** [comment]
@shwetagurnani 
In case, after reading the description, you feel like you will not be able to do this,please let me know!
