### ISSUE TITLE
Make our website responsive

### ISSUE THREAD

**Issue by rajats98** [CropAi/Frontend#103]
index.html
Update bootstrap to the latest version (4.4.1)
update bootstrap to latest version and update pages according to that, no scrolling on any page (expect result page, when content is large, only vertical scroll), no horizontal scroll in any case

Use bootstrap extensively to design, position(spacing and size, etc.) elements

colors/design may be changed, it must look aesthetic.
remove/update the redundant CSS on the go.
**Make the design responsive**

Before starting with it, understand what each and every element does.
Understand the flow of the whole code and website.
No functionality should be changed, no functionality should be broken.

If there is any doubt, Kindly ask.
Code neatly, Comment nicely!!

This issue will be assigned to @abhu-A-J, considering the previous contributions and understanding of the code.

**Comment by annu12340** [comment]
Can I take this issue?

**Comment by Satyam3976** [comment]
Can I

**Comment by shwetagurnani** [comment]
pls assign me this issue

**Comment by rajats98** [comment]
Sorry guys,
This assignee of this issue is predetermined based on performance till now,
@abhu-A-J you may remove your comments from other issues, and comment here
I hope you guys understand.

**Comment by abhushanaj** [comment]
> Sorry guys,
> This assignee of this issue is predetermined based on performance till now,
> @abhu-A-J you may remove your comments from issue, and comment here
> I hope you guys understand.

Ooops!! I thought I commented on 102!! Correcting the mistake right now!

**Comment by rajats98** [comment]
remove your comment from #99 also

**Comment by abhushanaj** [comment]
> remove your comment from #99 also

It's not there Sir, I deleted it after I read the details!
