### ISSUE TITLE
Create contributors page 

### ISSUE THREAD

**Issue by rajats98** [CropAi/Frontend#106]
Create a folder **contributors page** inside src (name the form exactly same)
create a file contributors.html
Check designs/contributors/contributors-4, we need a similar page with few changes in it 	
1. Navbar will have only 2 links on right( HOME, ANALYZE CROP NOW)
2. Add two buttons/tabs (Participant, Mentor and admins) below the CONTRIBUTORS heading  (towards left)
3. Only Add Github(out of 3 in design) icons in card(you may use icon libraries like font Awesome for icons)
4. Page should be responsive
5. Use dummy data for now

Use the **latest bootstrap(4.4.1)** to design the page

In case of any doubt, Kindly ask
Code neatly, Comment nicely!!

Edit: Upgraded tag to hard (creating a responsive page from scratch)

**Comment by annu12340** [comment]
can i  work on this issue

**Comment by Satyam3976** [comment]
Can I?

**Comment by rajats98** [comment]
@Satyam3976 assigning this to you

**Comment by rajats98** [comment]
@annu12340 you were assigned one already today!

**Comment by annu12340** [comment]
> @annu12340 you were assigned one already today!

But that was a beginner one. There was nothing much to do it :)

**Comment by rajats98** [comment]
Yes, I see ... Don't worry, more issues to come tomorrow! 
Someone had to that too (beginner one)!

**Comment by annu12340** [comment]
ok 😃

**Comment by rajats98** [comment]
@Satyam3976 In case, after reading the description, you feel like you will not be able to do this,please let me know!
