### ISSUE TITLE
Update Nav Bar Links in Landing page 3 (landing3.html)

### ISSUE THREAD

**Issue by rajats98** [CropAi/Frontend#116]
landing3.html

	rename Product to Analyze Crop, link it to index.html?q=analysis (relative address to index.html)
	rename contact us to Team, link it to contributors.html (src/contributors page/contributor.html), use relative address

	Also Link the Start analysing button to index.html?q=analyze

**Comment by abhishekgupta368** [comment]
I can do it. Can you assign me ?

**Comment by Adyasha8105** [comment]
Can I work on this issue?

**Comment by Satyam3976** [comment]
Can I

**Comment by rajats98** [comment]
@Satyam3976 Assigning this to you!

If there is any doubt, Kindly ask.
Code neatly, Comment nicely!!

**Comment by Adyasha8105** [comment]
@Satyam3976 Are you working on this?

**Comment by Satyam3976** [comment]
@rajats98 Relative address of index.html is index.html?q=analyze not index.html?q=analysis. If you want you can edit the description of this issue.
