### ISSUE TITLE
Update Nav Bar Links in Landing page 2 (landing2.html)

### ISSUE THREAD

**Issue by rajats98** [CropAi/Frontend#117]
landing2.html
Navbar links

	remove Blog And Contact Us from navBar
	rename Product to Analyze Crop, link it to index.html?q=analysis (relative address to index.html)
	link Team to contributors.html (src/contributors page/contributor.html)

	Also Link the Analyze button to index.html?q=analysis

**Comment by abhishekgupta368** [comment]
I can do it. Can you assign me ?

**Comment by Adyasha8105** [comment]
Can I work on this issue?

**Comment by Satyam3976** [comment]
Can I ?

**Comment by Adyasha8105** [comment]
@rajats98  assign this issue to me?
I have to change some other parts also.

**Comment by rajats98** [comment]
@Adyasha8105 assigning this to you !
If there is any doubt, Kindly ask.
Code neatly, Comment nicely!!
