### ISSUE TITLE
Update navbar contibutor.html 

### ISSUE THREAD

**Issue by rajats98** [CropAi/Frontend#118]
src/contributors page
contributor.html

navbar --> link ANALYZE CROP NOW to index.html?q=analysis (relative address to index.html)

move contributor.css to assets and update the same in contributor.html

**Comment by Adyasha8105** [comment]
Can I work on this issue?

**Comment by Satyam3976** [comment]
Can i

**Comment by Sapna2001** [comment]
Can I work on this?

**Comment by rajats98** [comment]
@Sapna2001 assigning this to you


If there is any doubt, Kindly ask.
Code neatly, Comment nicely!!
