### ISSUE TITLE
Add dummy image in input_container, index.html

### ISSUE THREAD

**Issue by rajats98** [CropAi/Frontend#119]
index.html

dummy image on form instead of empty image
download empty image icon/pic
show it input container's form

**Comment by Satyam3976** [comment]
Can I

**Comment by Adyasha8105** [comment]
Can I work on this issue?

**Comment by Adyasha8105** [comment]
Can I work on this issue?

**Comment by abhushanaj** [comment]
May I? Somehow I always get index.html!  😆

**Comment by rajats98** [comment]
@abhu-A-J assigning this to you

If there is any doubt, Kindly ask.
Code neatly, Comment nicely!!
