### ISSUE TITLE
basic details in Index.html

### ISSUE THREAD

**Issue by rajats98** [CropAi/Frontend#120]
add this line on index.html 

(to be shown on the bottom of the screen)
This is an Open Source project, created with love by `Contributors` under `GirlScript Summer of Code 2020`, conducted by `GirlScript Foundation`.

Add link to Contributors.html and gssoc,  girlscript websites (all to be opened in new tab)

**Comment by abhishekgupta368** [comment]
I can do it. Can you assign me ?

**Comment by Satyam3976** [comment]
Can I

**Comment by Adyasha8105** [comment]
Can I work on this issue?

**Comment by abhishekgupta368** [comment]
assign me this, please

**Comment by Sapna2001** [comment]
Can I work on this.

**Comment by abhushanaj** [comment]
@rajats98 Sir May I ?? Although I'm late !  😢

**Comment by rajats98** [comment]
@abhishekgupta368 assigning this to you!

If there is any doubt, Kindly ask.
Code neatly, Comment nicely!!
