### ISSUE TITLE
Add logo in title bar (favicon)

### ISSUE THREAD

**Issue by rajats98** [CropAi/Frontend#121]
Add logo in the title bar (favicon)
you may add a resized logo, name it appropriately if added (designs/logo-designs)

**Comment by Satyam3976** [comment]
Can i

**Comment by Adyasha8105** [comment]
Can I work on this issue?

**Comment by abhushanaj** [comment]
Can I do this one as well together with my previous one??

**Comment by rajats98** [comment]
> Can I do this one as well together with my previous one??


No!

**Comment by Adyasha8105** [comment]
@rajats98 Can I work on this part ???
As I have completed my previous task.

**Comment by Mustafiz04** [comment]
I would like to work on it. Sir @rajats98 please assign to me.

**Comment by rajats98** [comment]
@Mustafiz04 assigning this to you!
