### ISSUE TITLE
update readme

### ISSUE THREAD

**Issue by rajats98** [CropAi/Frontend#122]
update gssoc logo in readme 
go to https://miro.medium.com/max/1400/1*CKaCnG11p5i0KiQyaoyBvg.png
save the logo and add it to designs/logo-designs name gssoc-logo-with-text and update the logo in readme to this, give appropriate dimension 

Take **About girlscript** and **About gssoc's** (first para from both)  from gssoc.tech and add it under Important notice suitably

Update link and text of CONTRIBUTE.MD to CONTRIBUTING.MD (inside README.md)

**Comment by annu12340** [comment]
can i work on this issue

**Comment by Adyasha8105** [comment]
Can I work on this issue?

**Comment by Sapna2001** [comment]
Can I work on this.

**Comment by rajats98** [comment]
@annu12340 assigning this to you!
