### ISSUE TITLE
CSS issue file upload button

### ISSUE THREAD

**Issue by ashishnagpal2498** [CropAi/Frontend#129]
The file upload input box goes out of the container.
The pointer as cursor shows only at some places.

Screenshot
![image](https://user-images.githubusercontent.com/36301481/79045347-3b152900-7c28-11ea-8e95-34194857764f.png)

I would like to work on this issue as part of GSSOC 20.

**Comment by rajats98** [comment]
yes start working on this issue, I would suggest you to trigger **click on input** when the button is pressed.

**Comment by ashishnagpal2498** [comment]
Okay , I'll do that.
