### ISSUE TITLE
Add details about Data Modelling in Frontend/README

### ISSUE THREAD

**Issue by rajats98** [CropAi/Frontend#13]
Update Frontend/README.md 

Under heading IMPORTANT LINKS, add details about data-modeling repo in brief (tech-stack, techniques, dataset etc.),  give it a heading (eg. Data-Modeling)
the link to repo should be there

**Comment by scortier** [comment]
@rajats98  Sir, I want to work on this issue, So please assign me this issue.

**Comment by rajats98** [comment]
@Adyasha8105, you need to comment here so that I can assign

**Comment by Adyasha8105** [comment]
Please assign this task to me?

**Comment by Sulekhiya** [comment]
@Adyasha8105  are you still working on this issue?

**Comment by Adyasha8105** [comment]
Yes

**Comment by Adyasha8105** [comment]
@rajats98 I have a doubt regarding this:
Data-modeling repo in brief (tech-stack, techniques, dataset etc.)
How to get all this?

**Comment by Adyasha8105** [comment]
@rajats98 Sir, can you tell me how to do this?

**Comment by Sulekhiya** [comment]
You have to give a brief yourself. You can look our Slack channel for our timeline which contains tech-stacks techniques etc.

**Comment by rajats98** [comment]
I will be accepting 2 PRs for this issue so that we can get diversified content!

**Comment by Adyasha8105** [comment]
Actually I don't know the data modeling part.

**Comment by rajats98** [comment]
If anyone wants to contribute to this issue may comment here, will be accepting two PRs for this

**Comment by rajats98** [comment]
We need a brief of Data-modelling repo how it works and what tech stack is used, what does the data-set is all about...what models, maybe how many layers are used and anything you feel relevant.
Anyone who worked on data-modeling repo and know the whole overview is preferred.

**Comment by annu12340** [comment]
I am interested to work on this issue

**Comment by rajats98** [comment]
> We need a brief of Data-modelling repo how it works and what tech stack is used, what does the data-set is all about...what models, maybe how many layers are used and anything you feel relevant.
> Anyone who worked on data-modeling repo and know the whole overview is preferred.

@annu12340 Make sure you know these things for our project!!,
I am assigning this to you, you must confirm about the former line by a comment.

**Comment by rajats98** [comment]
@scortier If you want to add/modify something, Do it by today!
