### ISSUE TITLE
Text display After Image upload

### ISSUE THREAD

**Issue by ashishnagpal2498** [CropAi/Frontend#130]
The text displayed after image upload should be "image preview" or something else but shouldn't be upload an image.
Also after image upload the upload button should be changed to "change image button" 

Screenshot
![image](https://user-images.githubusercontent.com/36301481/79045603-9d225e00-7c29-11ea-8e16-46b827cd9592.png)

I would like to work on this issue as part of GSSOC 20.

**Comment by rajats98** [comment]
Update the heading to "Upload Crop Image", no need to change it after image upload.

Yes for the button change it to "Upload Image"(before upload) and 
After upload--> Change Image/Select another Image ( Whatever you feel like more relevant)

Make sure you understand the code properly first!
Code neatly, Comment nicely!!

**Comment by ashishnagpal2498** [comment]
Kindly merge the PR for issue #129  as it will create conflicts on changing text of button.
