### ISSUE TITLE
Collapse Navbar for landing page 3 

### ISSUE THREAD

**Issue by Satyam3976** [CropAi/Frontend#133]
![Screenshot from 2020-04-12 16-01-49](https://user-images.githubusercontent.com/25302027/79066646-25127180-7cd7-11ea-9c45-06e0e9b9d40f.png)

**Comment by Satyam3976** [comment]
![Screenshot from 2020-04-12 15-39-45](https://user-images.githubusercontent.com/25302027/79066658-3fe4e600-7cd7-11ea-9d80-426c41b03127.png)
On scrolling down, Crop AI text is hiding, We can also fix that

**Comment by rajats98** [comment]
It's okay, We don't require to work on this, Anyways on scrolling things have to move and leave the page.
