### ISSUE TITLE
Collapse Navbar for landing page 2

### ISSUE THREAD

**Issue by Satyam3976** [CropAi/Frontend#134]
The font of the navbar is too small, which is looking odd and difficult to read.

**Comment by Satyam3976** [comment]
![Screenshot from 2020-04-12 16-07-19](https://user-images.githubusercontent.com/25302027/79066728-de714700-7cd7-11ea-82ff-9d1c51b453bb.png)

**Comment by rajats98** [comment]
It's okay, as it is! The font is good enough, I will check once again and reopen the issue, if it is so
