### ISSUE TITLE
Landing Page 2 logo bug

### ISSUE THREAD

**Issue by Satyam3976** [CropAi/Frontend#135]
Landing Page 2 should have a href like the other 2 landing pages.

**Comment by rajats98** [comment]
why do you think that? it should be a href ?

**Comment by rajats98** [comment]
and where should it redirect to?

**Comment by Satyam3976** [comment]
Logo should always have a href which will redirect to the same page like the other 2 landing pages.

**Comment by rajats98** [comment]
Does it serve anything here? We we will move a to different page on clicking anything where it is not present, if the same navbar was to place on many pages, then it would have been a great idea. 
It is a single independent page, So it will redirect to itself, only, no purpose solved.

And on index.html it is required as it would help to return from other urls to landing page, for landing page3 , it was added, so it does not make any harm, that is why it is there (no issue to remove that also)


I really do not want to suppress any issue, but the issues should be a bit more relevant!

**Comment by Satyam3976** [comment]
It's perfectly alright sir, Just analyzing some issues and discussing here.
