### ISSUE TITLE
Analyze Crop Section

### ISSUE THREAD

**Issue by Satyam3976** [CropAi/Frontend#137]
When we are clicking on Analyze crop in the navbar. There is no way to go back to the same landing page as we redirect to index.html. So we should have an Analyze crop section for each page which will be shown on the same landing page so the user can have the option to go back to the same landing page.

**Comment by abhushanaj** [comment]
@Satyam3976  I think the index.html is our main page and I'm thinking the other landing pages were made so everyone get's to work on the project. So some functionality will not be present on it/or might break also. Anyhow I think Sir is there to clarify this!

**Comment by rajats98** [comment]
Satyam those landing pages are designed for later, we may replace the current landing page with anyone of them. : )
