### ISSUE TITLE
Improvement in alert message

### ISSUE THREAD

**Issue by ashishnagpal2498** [CropAi/Frontend#143]
- **Improvement in UI**
While uploading an image if the text field is empty , an alert box is shown which can be changed to an error message above text field.
![image](https://user-images.githubusercontent.com/36301481/79074063-e77a0c80-7d07-11ea-88ea-5a3119a4fb86.png)

**Comment by Yashank18** [comment]
I would like to work on it :)

**Comment by rajats98** [comment]
@ashishnagpal2498 do you want to work on this issue, or should I assign it to @Yashank18

**Comment by rajats98** [comment]
Label for the issue will be easy, as proper event listeners have already been set.

**Comment by ashishnagpal2498** [comment]
Yes , I want to work on this issue.

**Comment by rajats98** [comment]
@ashishnagpal2498 assigning this to you
