### ISSUE TITLE
Analysis Report CSS enhancement

### ISSUE THREAD

**Issue by shreyakapoor08** [CropAi/Frontend#145]
- **I'm submitting a ...**

  - [x] bug report
  - [ ] feature request

- **Do you want to request a feature or report a bug?**
Bug

- **What is the current behavior?**
1. Uploaded image is overlapping the text.
![image](https://user-images.githubusercontent.com/31164665/79141334-3e9ae280-7dd7-11ea-8a39-c7ecc9223a3a.png)

- **What is the expected behavior?**
1. Their should be some space between it.

**Comment by rajats98** [comment]
@shreyakapoor08 do you want to work on this?

**Comment by shreyakapoor08** [comment]
Yes I want to work on this ☺ @rajats98

**Comment by rajats98** [comment]
@shreyakapoor08 Submit it by tomorrow morning and make sure to pull the latest code.
