### ISSUE TITLE
correct closing button tag of Analyze in index.html 

### ISSUE THREAD

**Issue by rajats98** [CropAi/Frontend#147]
correct closing button tag of Analyze button in index.html 

Pull the code before making PR, you might encounter merge conflicts,
try to Resolve merge conflicts at your end.
If there is any doubt, Kindly ask.
Code neatly, Comment nicely!!

**Comment by Satyam3976** [comment]
Can I

**Comment by shwetagurnani** [comment]
can i work on it

**Comment by Adyasha8105** [comment]
can i?

**Comment by shreyakapoor08** [comment]
can I work on this?

**Comment by rajats98** [comment]
@Adyasha8105 assigning this to you
