### ISSUE TITLE
Minor design change

### ISSUE THREAD

**Issue by rajats98** [CropAi/Frontend#148]
index.html
for bottom line(This is an Open Source......)
Show links in red in all case(expect hover)

Pull the code before making PR, you might encounter merge conflicts,
try to Resolve merge conflicts at your end.
If there is any doubt, Kindly ask.
Code neatly, Comment nicely!!

**Comment by goyalmuskan** [comment]
May I?

**Comment by shwetagurnani** [comment]
can I

**Comment by Adyasha8105** [comment]
may i?

**Comment by shreyakapoor08** [comment]
can I work on this?

**Comment by Adyasha8105** [comment]
can i?

**Comment by Mustafiz04** [comment]
can I do this?? @rajats98 please assign this to me

**Comment by ashishnagpal2498** [comment]
Can I work on this issue ?

**Comment by rajats98** [comment]
@shreyakapoor08 you are currently assigned 2 issues, already!
So, @Mustafiz04 assigning this to you!
