### ISSUE TITLE
Show image on Result (on smaller screen sizes too)

### ISSUE THREAD

**Issue by rajats98** [CropAi/Frontend#149]
index.html
image on result page not shown on small screen
Show and Place it at a suitable position for small screens

Pull the code before making PR, you might encounter merge conflicts,
try to Resolve merge conflicts at your end.
If there is any doubt, Kindly ask.
Code neatly, Comment nicely!!

**Comment by Satyam3976** [comment]
Can I

**Comment by goyalmuskan** [comment]
May I work on this? @rajats98

**Comment by Adyasha8105** [comment]
May i?

**Comment by rajats98** [comment]
@goyalmuskan assigning this to you!
