### ISSUE TITLE
Show name of uploaded file

### ISSUE THREAD

**Issue by rajats98** [CropAi/Frontend#150]
index.html
in input_container
Show name of uploaded file below image

Pull the code before making PR, you might encounter merge conflicts,
try to Resolve merge conflicts at your end.
If there is any doubt, Kindly ask.
Code neatly, Comment nicely!!

**Comment by abhishekgupta368** [comment]
i can do it

**Comment by shwetagurnani** [comment]
can i

**Comment by Adyasha8105** [comment]
can i?

**Comment by shreyakapoor08** [comment]
can I work on this?

**Comment by rajats98** [comment]
@abhishekgupta368 assigning this to you
