### ISSUE TITLE
create default_contributors.js

### ISSUE THREAD

**Issue by rajats98** [CropAi/Frontend#151]
create a temporary Html file, include script_for_fetching_userdata as a script  **(temporary Html file to be deleted before making PR).** 

open the html file in browser, open console, copy the consoled object(it contains contributors_data)
refer this:

![JadedUnsteadyFennecfox-size_restricted](https://user-images.githubusercontent.com/33171120/79202059-a3e1e880-7e56-11ea-9617-0ecab725f619.gif)

create **default_contributors.js** (inside src/contributors page/)
create a const named **contributor_data_default** (exact) and store the copied object in it.

Pull the code before making PR, you might encounter merge conflicts,
try to Resolve merge conflicts at your end.
If there is any doubt, Kindly ask.
Code neatly, Comment nicely!!

**Comment by shwetagurnani** [comment]
Can I

**Comment by shwetagurnani** [comment]
Please assign it to me

**Comment by rajats98** [comment]
@shwetagurnani assigning this to you!
