### ISSUE TITLE
Add scripts to Contributor.html

### ISSUE THREAD

**Issue by rajats98** [CropAi/Frontend#152]
_src/contributors page/contributors.html_

make **contributor.js** in src/

add **default_contributors.js** (_will be available inside src/contributors page/_ ), **script_for_fetching_userdata,js**, **contributor.js** in contributor.html (keep the order) as script in contributors.html

move **function call** of contributors_information, from script_for_fetching_userdata to contributors.js
and make sure the object is printed in the console when you open contributor.html in browser

Pull the code before making PR, you might encounter merge conflicts,
try to Resolve merge conflicts at your end.
If there is any doubt, Kindly ask.
Code neatly, Comment nicely!!

**Comment by Satyam3976** [comment]
Can I

**Comment by shwetagurnani** [comment]
can i

**Comment by rajats98** [comment]
@Satyam3976 assigning this to you!

**Comment by rajats98** [comment]
@Satyam3976 Submit your PR by tonight
