### ISSUE TITLE
Regex in JS for Image

### ISSUE THREAD

**Issue by ashishnagpal2498** [CropAi/Frontend#155]
- **Feature**
Although the field of file input is restricted to image in accept field of input, the user can change the dialog box to all files and select any random file. Selecting the random file will break the normal flow of UI.
Solution-
Apply regex and only if that passed , show the preview of image else show an error as filetype is not an image.

To Replicate Error -
1) Click on upload image
2) Select all files option in dialog box
3) Select a non image file.

Screenshot
1) 
![image](https://user-images.githubusercontent.com/36301481/79218375-eebb2a80-7e6d-11ea-9c90-c31948ef23dd.png)
2) 
![image](https://user-images.githubusercontent.com/36301481/79218408-fda1dd00-7e6d-11ea-8496-bd21c0133036.png)

**Comment by rajats98** [comment]
You can directly pull out extn and compare it with what we require .
if you want to use regex, No issues!
Assigining this to you @ashishnagpal2498, In case you don't want to work on this issue, let me know
