### ISSUE TITLE
Share screenshots of successful working of backend [OPEN FOR ALL] 

### ISSUE THREAD

**Issue by rajats98** [CropAi/Frontend#157]
The backend is now complete, you need to setup the backend locally, to integrate API. 
Setup backend, And **Make a PR to https://github.com/CropAi/Backend/issues/85 in that repository** itself.
I would suggest in case of any issue or any kind of help in setup, Ask it on #proj_cropAi slack channel, It will help in building a strong community. Help others also!! 
If you issue in resolved there, feel free to message me or @tanishq9 on slack

### **_DON'T CREATE PR ON THIS REPO!!_**

**EDIT: We have deployed our backend, so the participants who want to work only on the frontend part, are not required to the setup backend locally.**

**Comment by abhushanaj** [comment]
Yay!!
