### ISSUE TITLE
Adding divs to contributor.html

### ISSUE THREAD

**Issue by rajats98** [CropAi/Frontend#164]
contributor.html
make 2 div with id "participants" and "mentors" [inside div.container (after the buttons)]

copy dummy contributor data in both the containers with different numbers of cards. [copy outer div with class row].

Do it ASAP!

If there is any doubt, Kindly ask.
Code neatly, Comment nicely!!

**Comment by Adyasha8105** [comment]
Can you assign this issue to me?

**Comment by shwetagurnani** [comment]
can I work on this issue?

**Comment by annu12340** [comment]
may i

**Comment by Adyasha8105** [comment]
Can you assign this issue to me?

**Comment by rajats98** [comment]
@Adyasha8105 assigning this to you
