### ISSUE TITLE
Make buttons working and style accordingly

### ISSUE THREAD

**Issue by rajats98** [CropAi/Frontend#165]
contributor.html
**to be done after issue #164 is resolved**

make buttons working and style accordingly
Buttons can be changed to divs and styling can be changed(if required)
change the order of buttons (i.e participants should be placed first)
initially, participants button will be active and div#participants will be displayed( div#mentor will be hidden).
on clicking admin and mentors, the admin and mentors will become active and div#mentors will be shown ( div#participants will be hidden)

at one time one button will be active and corresponding div would be shown

**Comment by abhu-A-J** [comment]
@rajats98 Sir May I ??

**Comment by abhishekgupta368** [comment]
I can do it. Can you assign me ?

**Comment by Satyam3976** [comment]
can I work on this issue?

**Comment by annu12340** [comment]
may i

**Comment by darkmatter18** [comment]
Assign me please

**Comment by rajats98** [comment]
@Satyam3976 Assigning it to you!

**Comment by rajats98** [comment]
@Satyam3976 you can start working on this, now #164 is closed

**Comment by shreyakapoor08** [comment]
can I work on this?

**Comment by rajats98** [comment]
@Satyam3976 Submit your PR by tomorrow morning!
