### ISSUE TITLE
Add script tag to contributor.html

### ISSUE THREAD

**Issue by rajats98** [CropAi/Frontend#166]
contributor.html
add user_palette.js as script tag (above other script tags)

**Comment by darkmatter18** [comment]
Assign please

**Comment by annu12340** [comment]
may i

**Comment by rajats98** [comment]
@darkmatter18 assigning this to you!

**Comment by darkmatter18** [comment]
@rajats98 Okk!!

**Comment by shreyakapoor08** [comment]
can I work on it?
