### ISSUE TITLE
Restyle About index.html

### ISSUE THREAD

**Issue by rajats98** [CropAi/Frontend#167]
index.html
About
add animation/transition on hide (you can also change,the on show animation/transition)
change font

**Comment by Adyasha8105** [comment]
Can you assign this issue to me?

**Comment by abhishekgupta368** [comment]
I can do it. Can you assign me ?

**Comment by shwetagurnani** [comment]
can I work on this issue?

**Comment by Satyam3976** [comment]
can I work on this issue?

**Comment by annu12340** [comment]
may i

**Comment by rajats98** [comment]
@abhishekgupta368  assigning this to you

**Comment by shreyakapoor08** [comment]
can I do this?
