### ISSUE TITLE
Bug: Input file, input and image not in sync [index.html]

### ISSUE THREAD

**Issue by rajats98** [CropAi/Frontend#168]
index.html
BUG fix:
After one image is selected and change/upload file is clicked and canceled in dialog box... the input[file] gets empty, but the image and name still show(prev one).
Either the input should not change to empty or the image/name to be removed

Label may be upgraded to Medium, after the PR is made!

If there is any doubt, Kindly ask.
Code neatly, Comment nicely!!

**Comment by shwetagurnani** [comment]
can I work on this issue?

**Comment by Satyam3976** [comment]
can I work on this issue?

**Comment by Satyam3976** [comment]
I want to work on this issue

**Comment by Adyasha8105** [comment]
Can you assign this issue to me?

**Comment by rajats98** [comment]
@shwetagurnani assigning this to you!
