### ISSUE TITLE
Integrate Api to fetch data

### ISSUE THREAD

**Issue by rajats98** [CropAi/Frontend#169]
index.js
API integration using ajax (fetch, XHR or jquery Ajax)
you need to create FormData object and image should be appended to it
key for image is "file" (key: value, file:(image))

endpoint: https://crop-leaf.herokuapp.com/file_upload
method: POST

headers: "Content-Type": "multipart/form-data"
body: formdata

console the response

If there is any doubt, Kindly ask.
Code neatly, Comment nicely!!

**Comment by abhushanaj** [comment]
@rajats98 Sir May I ??

**Comment by abhishekgupta368** [comment]
I can do it. Can you assign me ?

**Comment by Satyam3976** [comment]
can I work on this issue?

**Comment by shwetagurnani** [comment]
can I work on this issue?

**Comment by darkmatter18** [comment]
Assign me please

**Comment by rajats98** [comment]
@abhu-A-J Assigning this to you!
