### ISSUE TITLE
[OPEN FOR ALL] Update color_palette

### ISSUE THREAD

**Issue by rajats98** [CropAi/Frontend#170]
src/contributors page/user_palette.js

Add an object to array user_palette:
```
{
	background: "some color",
	color: "black"/"white"
}

```

the background and color will be applied as the image below, so check it on contributor/index.html, It should look good, the text should be clearly visible and easily readable.
![color_palette](https://user-images.githubusercontent.com/33171120/79536471-c285f080-809d-11ea-93ac-3f6cbed954ca.png)

**color**: choose only from black or white, which goes with your background
**background** can be any color(name/rbg), no gradient or design only solid/plain color

This issue is created to make the concept of **Merge Conflicts clear** , In case you get a merge conflict,  try resolving it and try to make sure the work of others is not removed!

**Refer these:** 
**_for updating your fork(pull the code from upstream)_**: https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/merging-an-upstream-repository-into-your-fork 

**_for resolving merge conflicts:_** https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/addressing-merge-conflicts
**[upstream refers to original repo, from which you forked... In our case it is https://github.com/CropAi/Frontend]**

In case you deliberately want a merge conflict to happen, pull the repo, add your changes commit them, wait for a few PRs to get merged and then pull the code again from this repo.
Otherwise, you can mention in PR that you want a merge conflict to happen.

### **NOTE: Make your PRs to dev branch**

If there is any doubt, Kindly ask.
Code neatly, Comment nicely!!

**EDIT: Currently addition to user_palette.js file will show no changes in contributor.html**

**Comment by Adyasha8105** [comment]
Can you assign this issue to me?

**Comment by darkmatter18** [comment]
Assign me please

**Comment by rajats98** [comment]
This issue is open for all, It does not need assignment, anyone can submit a PR!
