### ISSUE TITLE
Add hover effect on Contributors card contributor.html

### ISSUE THREAD

**Issue by rajats98** [CropAi/Frontend#173]
Add some hover effect on contributors card, maybe size change, or a bit of movement whatever you like

**Comment by annu12340** [comment]
can I work on this issue

**Comment by shreyakapoor08** [comment]
can I work on it?

**Comment by rajats98** [comment]
@annu12340 assigning this to you!

**Comment by rajats98** [comment]
> can I work on it?

@shreyakapoor08 No more issues to come today(so do not wait for new issue :sweat_smile: ) ! You can try the open to all issues! :100:
