### ISSUE TITLE
Create required directories

### ISSUE THREAD

**Issue by rajats98** [CropAi/Frontend#18]
1. Create folders as per this folder structure
  ```
  ../src
      ../assets
      ../img
      ../lib	
      ../landing pages
             ../landing page 2
             ../landing page 3
  ```

2. Rename style.css and script.js to index.js and index.css and move both files to assets.
And update index.html accordingly.

**Comment by abhushanaj** [comment]
@rajats98 I'll do this

**Comment by rajats98** [comment]
Assigned to you! @abhu-A-J

**Comment by abhu-A-J** [comment]
> Assigned to you! @abhu-A-J

What should I do with webdesigns folder?? Leave it as it is??
