### ISSUE TITLE
update card details [contributor.html]

### ISSUE THREAD

**Issue by rajats98** [CropAi/Frontend#187]
contributor.html
update card details
it will have:
github-username(in place of name)
No bio will be there
repositories the user worked upon => these should be designed as labels/tags(as you see on GitHub issue) give any bg color, and should be linked to corresponding repo(on click repo should open in new tab)

and github icon will remain there.

**Do it ASAP!!**

If there is any doubt, Kindly ask.
Code neatly, Comment nicely!!

**Comment by Satyam3976** [comment]
Can i

**Comment by shwetagurnani** [comment]
assign me

**Comment by darkmatter18** [comment]
Assign me please

**Comment by abhishekgupta368** [comment]
can i do it

**Comment by rajats98** [comment]
@Satyam3976 Assigning this to you!
