### ISSUE TITLE
create a function to create user_card [contributor.js]

### ISSUE THREAD

**Issue by rajats98** [CropAi/Frontend#188]
**contributor.js**

## TO BE DONE AFTER ISSUE #187 is resolved

create a function **create_user_card(user)** to create cards ,

input parameter will be object like this
```
{
  "login": "tanishq9",
  "avatar_url": "https://avatars2.githubusercontent.com/u/35667308?v=4",
  "html_url": "https://github.com/tanishq9",
  "repository": [
    "Frontend",
    "Backend",
    "Data-Modeling",
    "Android-Application"
  ],
  "designation": "mentor"
}
```
for repository **tags/labels** fix four background colors (make seperate object for that in beginning of funtion like  {Frontend:color1,Android-Application:color2}, and while styling tags/labels set background as {bg_colors["repo name"]}, so that it is easier to change colors if required)
link github icon to {html_url}
**function creates the card and append it to div with id = {designation}**
 
In case you feel, more specifications(to resolve the issue) are required, we can discuss them!

If there is any doubt, Kindly ask.
Code neatly, Comment nicely!!

**Comment by abhushanaj** [comment]
@rajats98 Sir May I ??

**Comment by Satyam3976** [comment]
Can i

**Comment by darkmatter18** [comment]
Can I work on it?

**Comment by shwetagurnani** [comment]
assign me

**Comment by abhishekgupta368** [comment]
can i do it ?

**Comment by rajats98** [comment]
@abhu-A-J  Assigning this to you!

**Comment by rajats98** [comment]
@abhu-A-J you can start working!! #187 is resolved.
also, decrease the font size of tags!
