### ISSUE TITLE
Move file 

### ISSUE THREAD

**Issue by rajats98** [CropAi/Frontend#189]
move contributor.js inside assets and update contributors.html accordingly.

**Do it ASAP!!**

If there is any doubt, Kindly ask.
Code neatly, Comment nicely!!

**Comment by Sapna2001** [comment]
Can i work on this?

**Comment by abhishekgupta368** [comment]
can i do it?

**Comment by shwetagurnani** [comment]
assign me

**Comment by rajats98** [comment]
@Sapna2001 assigning this to you!
