### ISSUE TITLE
Update Script tags [contributor.html]

### ISSUE THREAD

**Issue by rajats98** [CropAi/Frontend#190]
Check script tags in contributor.html (check src, they can be shortened)
eg : ../contributors page/user_palette.js => ./user_palette.js

If there is any doubt, Kindly ask.
Code neatly, Comment nicely!!

**Comment by shwetagurnani** [comment]
assign me

**Comment by abhushanaj** [comment]
@rajats98 Sir I have already commented on #188  (which is my preference), but if I can take this one as well I would like to take it along with that since no one has commented on it.
**Only if it's possible!**

**Comment by abhishekgupta368** [comment]
I can do it.

**Comment by annu12340** [comment]
can i do it

**Comment by Adyasha8105** [comment]
Can I as I have completed my other task? @rajats98

**Comment by shreyakapoor08** [comment]
can i do this?

**Comment by rajats98** [comment]
@shreyakapoor08 Assigning this to you!
