### ISSUE TITLE
Update according to API response!

### ISSUE THREAD

**Issue by rajats98** [CropAi/Frontend#191]
index.js
in update_result function change report.Disease with report.category
(because the API returns disease name with "category" as the key)	
Do it ASAP!!

If there is any doubt, Kindly ask.
Code neatly, Comment nicely!!

**Comment by darkmatter18** [comment]
Assign me please

**Comment by shwetagurnani** [comment]
assign me

**Comment by abhishekgupta368** [comment]
i can do it

**Comment by rajats98** [comment]
@darkmatter18 assigning this to you!

**Comment by rajats98** [comment]
@darkmatter18 Submit this by tonight!

**Comment by Satyam3976** [comment]
@darkmatter18 If you have any doubt, feel free to ask it here or on slack.
