### ISSUE TITLE
Update result on ajax response [index.js]

### ISSUE THREAD

**Issue by rajats98** [CropAi/Frontend#192]
index.js
remove dummy data (analysis_report_json)
in validateAndDisplay function
		move code below the comment(//on successful response) to success in ajax.
		rename data recevied in success callback parameter as analysis_report_json.

If there is any doubt, Kindly ask.
Code neatly, Comment nicely!!

**Comment by abhishekgupta368** [comment]
i can do it

**Comment by shwetagurnani** [comment]
assign me

**Comment by annu12340** [comment]
can i

**Comment by rajats98** [comment]
@abhishekgupta368 Assigning this to you!
