### ISSUE TITLE
Update error call back Ajax [index.js]

### ISSUE THREAD

**Issue by rajats98** [CropAi/Frontend#193]
index.js 
in validateAndDisplay function
		on error call back rename parameter to err (from data),
		add an alert inside it, "Something went wrong, Please try again after some time"

If there is any doubt, Kindly ask.
Code neatly, Comment nicely!!

**Comment by abhishekgupta368** [comment]
i can do it

**Comment by annu12340** [comment]
can i

**Comment by rajats98** [comment]
@annu12340 Assigning this to you!
