### ISSUE TITLE
Remove unnecessary comments [index.js]

### ISSUE THREAD

**Issue by rajats98** [CropAi/Frontend#194]
index.js 

find this comment 
```
Process take place in following steps:
  1) Get DOM model of leaf_input
  2) Get DOM model of img-lab
  3) Pass the file name of leaf_input to img-lab
  4) Value will be subsitute on panel
```
and replace it with one line comment (//adding image name)

Remove commented code for form submission also

If there is any doubt, Kindly ask.
Code neatly, Comment nicely!!

**Comment by abhishekgupta368** [comment]
i can do it

**Comment by annu12340** [comment]
can i

**Comment by Adyasha8105** [comment]
can i?

**Comment by rajats98** [comment]
@Adyasha8105 assigning this to you!
