### ISSUE TITLE
remove outline from buttons [contributor.html]

### ISSUE THREAD

**Issue by rajats98** [CropAi/Frontend#195]
contributor.html
	remove outline(that appears on clicking/focus) from the buttons Participants and Admin and Mentors

If there is any doubt, Kindly ask.
Code neatly, Comment nicely!!

**Comment by shwetagurnani** [comment]
assign me

**Comment by Satyam3976** [comment]
Can I

**Comment by abhishekgupta368** [comment]
i can do it

**Comment by annu12340** [comment]
can i do it

**Comment by Adyasha8105** [comment]
can i?
