### ISSUE TITLE
Basic structure

### ISSUE THREAD

**Issue by rajats98** [CropAi/Frontend#20]
**../src/index.html** 

create a divs as described

```
div1 id:"background"
      div2 id: landing_container
      div3 id: input_container
      div4 id: result_container
```
i.e. one div enclosing 3 divs

**Comment by abhushanaj** [comment]
@rajats98 Sir May I do this?

**Comment by Sapna2001** [comment]
Can I work on this?

**Comment by rajats98** [comment]
@abhu-A-J assigning it to you, do it before 2pm
