### ISSUE TITLE
update default_contributors.js 

### ISSUE THREAD

**Issue by rajats98** [CropAi/Frontend#208]
open contributors.html in browser and from console copy the object 
refer #151 to check how to copy properly,
from default_contributors.js remove the previous value of default_contributors_data and paste the copied object

**Comment by Satyam3976** [comment]
@shwetagurnani You can take this bug, as I already have a comment on #213

**Comment by shwetagurnani** [comment]
Can you assign this issue to me?

**Comment by rajats98** [comment]
@shwetagurnani assigning this to you!
