### ISSUE TITLE
remove dummy data from contributor.html

### ISSUE THREAD

**Issue by rajats98** [CropAi/Frontend#209]
Remove Dummy data from contributor.html

**Comment by shwetagurnani** [comment]
Can you assign this issue to me?

**Comment by annu12340** [comment]
can i

**Comment by rajats98** [comment]
@annu12340 assigning this to you!

**Comment by rajats98** [comment]
@annu12340 submit this by today!

**Comment by Souvikns** [comment]
Sir, I have removed the dummy data from the contributions.html
https://github.com/CropAi/Frontend/pull/225

**Comment by annu12340** [comment]
I will do it shortly
