### ISSUE TITLE
Add gssoc profile to contributor's card

### ISSUE THREAD

**Issue by rajats98** [CropAi/Frontend#211]
contributor.html / js
add gssoc icon before github icon
link it to https://www.gssoc.tech/profile.html?id={login} [to be opened in new tab]
Changes to be done inside create_user_card. (create a const for link first)

**Comment by abhushanaj** [comment]
@rajats98 Sir May I ??

**Comment by Satyam3976** [comment]
Can I

**Comment by shwetagurnani** [comment]
can i

**Comment by annu12340** [comment]
can i

**Comment by rajats98** [comment]
@abhu-A-J assigning this to you!
