### ISSUE TITLE
show loading until response is recevied 

### ISSUE THREAD

**Issue by rajats98** [CropAi/Frontend#213]
index.html

after clicking submit show loading until response is received
hide both button and show loading icon
Check all use-cases properly. (e.g. it should show buttons while we use Analyze another crop from the result page)
Understand the current code first, and then start implementing!

**Comment by Satyam3976** [comment]
Can I

**Comment by shwetagurnani** [comment]
Can you assign this issue to me?

**Comment by darkmatter18** [comment]
Can I

**Comment by rajats98** [comment]
@Satyam3976 assigning this issue to you!

**Comment by annu12340** [comment]
can i
