### ISSUE TITLE
Small CSS Bug on cards

### ISSUE THREAD

**Issue by abhushanaj** [CropAi/Frontend#218]
- **I'm submitting a ...**

  - [x] bug report

- **What is the current behavior?**
  The contributor card on hover covers a portion of the buttons (first two cards on any screen size ) 

- **What is the expected behavior?**
 The scaling effect is nice but should be reduced a little, so contents don't get hidden as buttons are a way to switch between them.

- **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)

![Screenshot (150)](https://user-images.githubusercontent.com/49617450/79866938-2a6c6c00-83fb-11ea-89e5-ca97f2f200cb.png)

If it's considered valid I would like to change the CSS for it.

**Comment by rajats98** [comment]
It's fine, It does not create any problem! 
Only a small portion is hidden and that too on hover of another element.
