### ISSUE TITLE
Small CSS Bug on icons

### ISSUE THREAD

**Issue by abhushanaj** [CropAi/Frontend#219]
- **I'm submitting a ...**
 - [x] bug report

- **What is the current behavior?**
When the Github Icon is hovered it gives an underline effect (which does not make sense) since it's not a text neither a styling effect.

- **What is the expected behavior?**
Remove the underline effect on hovering over.

- **Other information** (e.g. detailed explanation, stack traces, related issues, suggestions how to fix, links for us to have context, eg. StackOverflow, Gitter, etc)

![Screenshot (152)](https://user-images.githubusercontent.com/49617450/79867236-a961a480-83fb-11ea-969d-67fdb418fdd6.png)

If considered valid I would like to address them, I think it's because of how natively `a`  tags behave on browsers.

**Comment by rajats98** [comment]
@abhu-A-J you can start working on this!
