### ISSUE TITLE
Move index.html

### ISSUE THREAD

**Issue by rajats98** [CropAi/Frontend#223]
Move index.html in root directory (move it outside of src) and update all link and script tags carefully!

EDIT: also update the navbar links in contributor.html

**Comment by shreyakapoor08** [comment]
can I do this?

**Comment by rajats98** [comment]
@shreyakapoor08 assigning this to you!

**Comment by scortier** [comment]
Sir , if possible can you allot me this task as till now i haven't merge any PR, i have created many pr but no merge are possible.

**Comment by rajats98** [comment]
@scortier This issue is already assigned to Shreya! 
For now, you can try #170.
Also, join this project's slack channel for to get updated about upcoming issues!

**Comment by rajats98** [comment]
@shreyakapoor08 also update the navbar links in contributor.html
