### ISSUE TITLE
Update heading 

### ISSUE THREAD

**Issue by rajats98** [CropAi/Frontend#229]
index.html 
In result section change heading
	Product to Recommended Product

**Comment by shwetagurnani** [comment]
can i

**Comment by abhishekgupta368** [comment]
I can do it. Can you assign me ?

**Comment by darkmatter18** [comment]
Assign

**Comment by annu12340** [comment]
can i

**Comment by pratyushraj7** [comment]
assign me

**Comment by Sapna2001** [comment]
Can i

**Comment by scortier** [comment]
Hello Sir , Plz can you assign me this task as it will be my first task to do in gssoc...plzzz.

**Comment by Aakansha99** [comment]
Kindly assign this issue to me

**Comment by rajats98** [comment]
@darkmatter18 assigning this to you!

**Comment by darkmatter18** [comment]
@rajats98 I didn't understand what to change. Is it this line ?  https://github.com/CropAi/Frontend/blob/c9b845fa15dae72a1e9e721fe474004c862d15a1/index.html#L111

**Comment by rajats98** [comment]
Recommended Products (instead of products only)
