### ISSUE TITLE
Update Title on different pages

### ISSUE THREAD

**Issue by rajats98** [CropAi/Frontend#230]
index.html/js
Update Title on different pages
Crop AI | Home
Crop AI | Analyze Crop
Crop AI | Analysis Report

**Comment by abhishekgupta368** [comment]
I can do it. Can you assign me ?

**Comment by abhu-A-J** [comment]
@rajats98 Sir May I ??

**Comment by darkmatter18** [comment]
Assign

**Comment by shwetagurnani** [comment]
can i

**Comment by pratyushraj7** [comment]
assign me please

**Comment by Satyam3976** [comment]
can i

**Comment by scortier** [comment]
Hello Sir , Plz can you assign me this task as it will be my first task to do in gssoc...plzzz.

**Comment by Aakansha99** [comment]
Kindly assign this issue to me

**Comment by rajats98** [comment]
@shwetagurnani assigning this to you!

**Comment by Adyasha8105** [comment]
Can i?
