### ISSUE TITLE
Show countdown while loading

### ISSUE THREAD

**Issue by rajats98** [CropAi/Frontend#231]
index.html 
show 30-sec countdown on while loading result (

**Comment by abhu-A-J** [comment]
@rajats98 Sir May I ??

**Comment by abhishekgupta368** [comment]
I can do it. Can you assign me ?

**Comment by darkmatter18** [comment]
Assign

**Comment by Satyam3976** [comment]
can i

**Comment by annu12340** [comment]
I can do it.

**Comment by shwetagurnani** [comment]
can i

**Comment by Aakansha99** [comment]
Kindly assign this issue to me

**Comment by scortier** [comment]
Hello Sir , Plz can you assign me this task as it will be my first task to do in gssoc...plzzz.

**Comment by rajats98** [comment]
@annu12340 assigning this to you!

**Comment by Adyasha8105** [comment]
Can i?

**Comment by rajats98** [comment]
@annu12340 Submit this today!!

**Comment by abhishekgupta368** [comment]
please, allow me to do that, I will submit today only
