### ISSUE TITLE
Open product links in new tab

### ISSUE THREAD

**Issue by rajats98** [CropAi/Frontend#232]
index.js
The links for product should open in new tabs
find the relevant code in update_result function

**Comment by darkmatter18** [comment]
Assign

**Comment by abhishekgupta368** [comment]
I can do it. Can you assign me ?

**Comment by annu12340** [comment]
can i do it

**Comment by scortier** [comment]
Hello Sir , Plz can you assign me this task as it will be my first task to do in gssoc...plzzz.

**Comment by Aakansha99** [comment]
Could you please assign this issue to me

**Comment by rajats98** [comment]
@abhishekgupta368 assigning this to you!
