### ISSUE TITLE
Delete commented code

### ISSUE THREAD

**Issue by rajats98** [CropAi/Frontend#233]
index.js
delete commented code for dummy data i.e const analysis_report_json

**Comment by abhishekgupta368** [comment]
I can do it. Can you assign me ?

**Comment by pratyushraj7** [comment]
can u assign me ?

**Comment by annu12340** [comment]
can i do it

**Comment by Sapna2001** [comment]
Can i

**Comment by scortier** [comment]
Hello Sir , Plz can you assign me this task as it will be my first task to do in gssoc...plzzz.

**Comment by Adyasha8105** [comment]
can i?

**Comment by rajats98** [comment]
@pratyushraj7 assigning this to you
