### ISSUE TITLE
update url scheme(ROUTES)

### ISSUE THREAD

**Issue by rajats98** [CropAi/Frontend#234]
index.html/js
###create PR on dev branch
check and update url scheme(ROUTES) to /analyze, /result 
eg. https://cropai.netlify.app/analyze (instead of https://cropai.netlify.app/index.html?q=analyze or https://cropai.netlify.app/?q=analyze)
you will need to create a localhost server,
Refer this: https://stackoverflow.com/questions/38497334/how-to-run-html-file-on-localhost (you can choose any one method)

**Comment by abhushanaj** [comment]
@rajats98 Sir May I ??

**Comment by darkmatter18** [comment]
Assign

**Comment by abhishekgupta368** [comment]
I can do it. Can you assign me ?

**Comment by shwetagurnani** [comment]
can i

**Comment by annu12340** [comment]
can i do it

**Comment by rajats98** [comment]
@abhu-A-J assigning this to you!

**Comment by abhushanaj** [comment]
> @abhu-A-J assigning this to you!

Thank you!
