### ISSUE TITLE
Add random colors to card

### ISSUE THREAD

**Issue by rajats98** [CropAi/Frontend#235]
contributor.html/js
Add colors to cards
Select a random color object from user_palette array for each card and apply it to div with class card-body

**Comment by Satyam3976** [comment]
can i\

**Comment by abhishekgupta368** [comment]
I can do it. Can you assign me ?

**Comment by shwetagurnani** [comment]
can i

**Comment by Aakansha99** [comment]
Kindly assign this issue to me

**Comment by rajats98** [comment]
@Satyam3976 assigning this to you!
