### ISSUE TITLE
Add title contributor

### ISSUE THREAD

**Issue by rajats98** [CropAi/Frontend#236]
contributors.html
Add a suitable title

**Comment by abhishekgupta368** [comment]
I can do it. Can you assign me ?

**Comment by pratyushraj7** [comment]
can u assign me?

**Comment by Sapna2001** [comment]
Can i

**Comment by Aakansha99** [comment]
Could you please assign this to me?

**Comment by scortier** [comment]
Hello Sir , Plz can you assign me this task .

**Comment by Adyasha8105** [comment]
can i?

**Comment by rajats98** [comment]
@Sapna2001 assigned this to you!
