### ISSUE TITLE
Show some hover effect on icons

### ISSUE THREAD

**Issue by rajats98** [CropAi/Frontend#237]
contributors.html/css
show hover effect on gssoc and github icon
(some very simple hover effects, so that hover is easily distinguished!)

**Comment by abhishekgupta368** [comment]
I can do it. Can you assign me ?

**Comment by annu12340** [comment]
can i

**Comment by Aakansha99** [comment]
Kindly assign this issue to me

**Comment by Adyasha8105** [comment]
can i?

**Comment by rajats98** [comment]
@scortier do you want to work on this?

**Comment by rajats98** [comment]
@Adyasha8105 assigning this to you!
