### ISSUE TITLE
remove redundant code

### ISSUE THREAD

**Issue by rajats98** [CropAi/Frontend#238]
fade class(index.css) might be redundant
first, carefully check, if it is not used-> remove (you need to check index.html and  js files linked to it )
If it is used somewhere tell

**Comment by Aakansha99** [comment]
Kindly assign this issue to me

**Comment by rajats98** [comment]
@Aakansha99 assigning this to you!

**Comment by rajats98** [comment]
@Aakansha99 Do this ASAP!
