### ISSUE TITLE
user_cards bottom corners are not round

### ISSUE THREAD

**Issue by rajats98** [CropAi/Frontend#239]
contributors.html /js
bottom corners of the card are not round 
check by giving background color to div with class card-body
first Discuss how you will do it and then update create_user_card in contributor.js accordingly

**Comment by abhishekgupta368** [comment]
can you assign me, I will do both of it

**Comment by darkmatter18** [comment]
Assign

**Comment by rajats98** [comment]
@scortier Do you want to work on this?

**Comment by shreyakapoor08** [comment]
can I work on it?

**Comment by abhishekgupta368** [comment]
can I do it now?

**Comment by rajats98** [comment]
@shreyakapoor08 assigning this to you!
