### ISSUE TITLE
Improvement on LP3

### ISSUE THREAD

**Issue by abhushanaj** [CropAi/Frontend#249]
**I'm submitting a ...**
- [x] bug report on Landing Page Three

 **What is the current behavior?**
-  The page is scrollable
-  The scroll the navigation bar goes in the top of content (navbar is way bigger than it's content)
- Scripts are written in between HTML (makes it difficult to read HTML)
- Many styles are inline, even though separate stylesheet is given
- The content sizes are very big compared to the screen sizes
- Layout breaks on few devices and few responsiveness issues on small devices (Screenshots below)
- Navbar is not hamburger style ( **not sure if it is meant to be like that so need validation on this**)

 **What is the expected behavior?**
- Hopefully Correction of above and moving stylesheets and JS to necessary files.

 **Other information** 

## Scrollable Issue with Navbar
![Screenshot (156)](https://user-images.githubusercontent.com/49617450/80121494-026f3b00-85aa-11ea-940a-48a929667b75.png)

## Overlapping Content on Smaller Screens
![Screenshot (162)](https://user-images.githubusercontent.com/49617450/80121535-0bf8a300-85aa-11ea-809d-26ed32c67e60.png)

## Inline Styles and Scripts
![Screenshot (163)](https://user-images.githubusercontent.com/49617450/80121626-2c286200-85aa-11ea-9a1f-4c7c1e4a315f.png)

## Breaking Laoyouts
![Screenshot (160)](https://user-images.githubusercontent.com/49617450/80121881-6f82d080-85aa-11ea-9a7f-80075c0d9106.png)

@rajats98 Sir, if valid I'd like to propose myself as a potential candidate. Thank you!

**Comment by rajats98** [comment]
@abhu-A-J actually the design is kept like this after discussion, The scroll gives a nice smooth effect on navbar. 
refer #133, On small screen content overlaps on scrolling, so it is cool, It looks cool (according to me), the navbars transparency increases when the content is behind.
hamburger for navbar is not required, it is designed like this.

Script point is valid, but it is very compact, I don't think increasing a file for this is a good option.


- still, if you want, you are allowed to make new files for script,
         
         (do for both lp2, lp3)
         make script files in respective folder
         also move css files to respective fol der

- Correct the bugs related to different breakpoints/responsive
- if feasible move inline designs to css file
- If you strongly feel like something else should be fixed, we can discuss.

**Comment by rajats98** [comment]
labels might change after PR review
