### ISSUE TITLE
create Background for landing page2

### ISSUE THREAD

**Issue by rajats98** [CropAi/Frontend#25]
refer landing page of **design-2** in **Web Designs** 

Create almost the same background as you see in the picture, find the resources in design-2 folder itself. **(do not create any button, links, text)**

**Comment by abhushanaj** [comment]
@rajats98 Sir Can I do this?

**Comment by annu12340** [comment]
I would like to work on this

**Comment by rajats98** [comment]
Yes, Assigned to you @abhu-A-J

**Comment by rajats98** [comment]
Make sure your it occupies the whole screen, and no scrolling should be there

**Comment by abhushanaj** [comment]
> Make sure your it occupies the whole screen, and no scrolling should be there

@rajats98 
Sir just to clarify, I should change landing2.html page and not the main index.html page.??
Also the images on the right of farmers comes as background?? Because background is just white in color??
