### ISSUE TITLE
Fix indentation in index.js file

### ISSUE THREAD

**Issue by shwetagurnani** [CropAi/Frontend#251]
- **I'm submitting a ...**

  - [x] Code styling
  - [ ] bug report
  - [ ] feature request

- **Do you want to request a feature or report a bug?**

- **What is the current behavior?**
Indentation is not correct in index.js file
- **What is the expected behavior?**
Identation should be correct.
- **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)

**Comment by shwetagurnani** [comment]
I want to work on it!

**Comment by rajats98** [comment]
use tabs only for indenting! 
assigning this to you @shwetagurnani !
