### ISSUE TITLE
Add Comments in index.js

### ISSUE THREAD

**Issue by shwetagurnani** [CropAi/Frontend#253]
- **I'm submitting a ...**
  - [x] Code Styling
  - [ ] bug report
  - [ ] feature request

- **Do you want to request a feature or report a bug?**

- **What is the current behavior?**
   Some functions working is not explained using comments. I want to add some comments to explain their functionality.

- **What is the expected behavior?**
    Comments should be there to explain the functionality of the code.

- **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)

**Comment by shwetagurnani** [comment]
I want to work on this issue:)

**Comment by Aakansha99** [comment]
Kindly assign this issue to me

**Comment by ashishnagpal2498** [comment]
Can I work on this issue?

**Comment by rajats98** [comment]
@shwetagurnani submit this by today!
