### ISSUE TITLE
FIx indentation in landing-3.css

### ISSUE THREAD

**Issue by shwetagurnani** [CropAi/Frontend#254]
- **I'm submitting a ...**
  - [x] Code Styling
  - [ ] bug report
  - [ ] feature request

- **Do you want to request a feature or report a bug?**

- **What is the current behavior?**
    Incorrect indentation in landing-3.css

- **What is the expected behavior?**
   Indentation should be correct(line 116-138)
![Screenshot from 2020-04-24 01-21-05](https://user-images.githubusercontent.com/43384092/80143551-9cdf7680-85ca-11ea-9058-29f4afed861d.png)

- **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)

**Comment by shwetagurnani** [comment]
I want to work on this issue:)

**Comment by Aakansha99** [comment]
Kindly assign this issue to me

**Comment by rajats98** [comment]
@shwetagurnani wait for #249 to resolve first, then will check if it is required, and the updated file may need more indentation!

**Comment by ashishnagpal2498** [comment]
Can I work on this issue?

**Comment by rajats98** [comment]
@shwetagurnani now you can work on this!

**Comment by gauraws** [comment]
Hey, I am beginner. Can I work on this issue?

**Comment by rajats98** [comment]
@gauraws you can't work on this issue, this is already assigned!
