### ISSUE TITLE
create Background for landing page3

### ISSUE THREAD

**Issue by rajats98** [CropAi/Frontend#26]
refer landing page of **design-3** in **Web Designs** 

Create almost the same background as you see in the picture, find the resources in design-3 folder itself. **(do not create any button, links, text)**

**Comment by annu12340** [comment]
I would like to work on this

**Comment by rajats98** [comment]
@annu12340, Assigning this issue to you

**Comment by rajats98** [comment]
Make sure your it occupies whole screen, and no scrolling should be there

**Comment by Adyasha8105** [comment]
@rajats98 Can I work on this issue?

**Comment by rajats98** [comment]
@annu12340 Do it before 10 AM tomorrow :).

**Comment by annu12340** [comment]
Could you please give me one more hour? I am almost done

**Comment by rajats98** [comment]
yes! try to do it ASAP

**Comment by annu12340** [comment]
ok 👍
