### ISSUE TITLE
UX improvement of image name

### ISSUE THREAD

**Issue by ashishnagpal2498** [CropAi/Frontend#260]
- **Feature**
  - [ ] feature request

- **What is the current behavior?**
![image](https://user-images.githubusercontent.com/36301481/80199112-9b4f9600-863e-11ea-82c4-0629964431bb.png)

- **What is the expected behavior?**
UX improvement-
- Color code of the image display name can be corrected.
- Responsive design
- tooltip on hover, shows complete name.

**Comment by rajats98** [comment]
Also make increase its length and reduce fontsize, and increase some character shown!

**Comment by rajats98** [comment]
@ashishnagpal2498 submit this by today!
