### ISSUE TITLE
Add links in contributor page

### ISSUE THREAD

**Issue by Adyasha8105** [CropAi/Frontend#270]
I think the links are not working i.e HOME and ANALYZE CROP.
@rajats98 I want to work on it.

screenshots:
![2020-04-25 (8)](https://user-images.githubusercontent.com/54095539/80281642-425d2c00-872a-11ea-95a7-748f809bbe96.png)

**Comment by abhushanaj** [comment]
@Adyasha8105 You need to run them on the server, since they are not relative anymore!

**Comment by Adyasha8105** [comment]
> @Adyasha8105 You need to run them on the server, since they are not relative anymore!

Okay, I got it :)
