### ISSUE TITLE
Correct alignment of Analyse other crop button

### ISSUE THREAD

**Issue by rajats98** [CropAi/Frontend#273]
Move Analyze other crop button to the center. (result section)

**Comment by darkmatter18** [comment]
Assign please

**Comment by pratyushraj7** [comment]
Can I do this?

**Comment by rajats98** [comment]
@darkmatter18 assigning this to you make PR on dev branch!

**Comment by rajats98** [comment]
@darkmatter18 also check about and analyse button on small screen size, they should also be horizontally centered.
upgrading this to easy!

**Comment by rajats98** [comment]
I think margin of 1rem is problem to class btn-container.. try removing it

**Comment by rajats98** [comment]
@darkmatter18 do this by today!
