### ISSUE TITLE
Update README

### ISSUE THREAD

**Issue by rajats98** [CropAi/Frontend#275]
Add a line for LICENSE. (see other repos, how should it be like)
Add a line to thank netlify and heroku for free hosting of our application!
Add links to hosted backend and frontend hyperlink (https://crop-leaf.herokuapp.com and https://cropai.netlify.app/) as hyperlink

**Comment by abhushanaj** [comment]
May I?

**Comment by shwetagurnani** [comment]
May I?

**Comment by afrozchakure** [comment]
May I ?

**Comment by Kuljeet-123** [comment]
@rajats98 Can I work on this??

**Comment by Satyam3976** [comment]
Can i work on it?

**Comment by rajats98** [comment]
@afrozchakure assigning this to you!

@abhu-A-J, @shwetagurnani  He is first-time contributor, So I think you guys understand!
also, @shwetagurnani you are already assigned 2 issues!

**Comment by rajats98** [comment]
@afrozchakure make your changes and PR on dev branch

**Comment by afrozchakure** [comment]
Ok @rajats98 :+1:

**Comment by gauraws** [comment]
Beginner here, can I work on this issue?

**Comment by rajats98** [comment]
@gauraws this is already assigned, So you can't!

**Comment by afrozchakure** [comment]
![image](https://user-images.githubusercontent.com/40469121/80346614-a269e480-8888-11ea-82fe-5e900dcd345f.png)

@rajats98, wanted to know is this fine or do you want any changes?

**Comment by rajats98** [comment]
Cool!

**Comment by rajats98** [comment]
@afrozchakure Thanks to our many contributors and to Netlify & Heroku for hosting our application.
Here we can link our contributors' page also, It would be great if you can update it to this!
contributors : https://cropai.netlify.app/src/contributors/
