### ISSUE TITLE
Cards bug 

### ISSUE THREAD

**Issue by abhushanaj** [CropAi/Frontend#277]
**I'm submitting a ...**
- [x] bug report
 
 **Do you want to request a feature or report a bug?**
Contributors Page (small width ) <=575px
- The cards issue and it's consequence discussed in details below.
- The heading should be 10-11px small to avoid scrolling on x-axis. 
- Making cards a little small so on click on links (a consequence of hover) it doesn't cover up all the buttons and we have to click on some empty space to come back to a normal state which technically isn't available since cards cover the entire width.

 **What is the current behavior?**
- Each card takes the entire screen width which means a card is around 575px in width, so it covers the entire screen.
- If you hover (click on small devices) it will go out of screen. Since it scales on top on 575px width and covers the button completely.

**What is the expected behavior?**
- The card should be smaller and have breathing space on the left and right. Pictures attached below to see the difference.
- Also solves the issue of when someone clicks on the links (since hover gets converted to click) on touch devices it will avoid the cards going out of the viewport (instead of on disabling hover on mobile devices )

 **Other information(Screenshots)** 
- How it looks:
![Screenshot (166)](https://user-images.githubusercontent.com/49617450/80307733-929ac380-87e8-11ea-907a-4fde3c01bd2f.png)

- How it should look
![Screenshot (167)](https://user-images.githubusercontent.com/49617450/80307741-9b8b9500-87e8-11ea-8116-48d2ab198619.png)

**Comment by rajats98** [comment]
Yup! reduce the card width(you can also decrease container width), and the "Contributors" heading size for small breakpoint
