### ISSUE TITLE
Update background of index.html

### ISSUE THREAD

**Issue by rajats98** [CropAi/Frontend#28]
Refer the landing page of **design-1** in **Web Designs**

Create almost the same background as you see in the picture, find the resources in design-1 folder itself. (do not create any button, links, text),i.e only the leaves, glass and bg color to be updated.

**Make sure your it occupies whole screen, and no scrolling should be there.
Do not touch the 3 internal divs leave them as it is work on outer div with id=background**

**Comment by abhishekgupta368** [comment]
i can do it

**Comment by darkmatter18** [comment]
@rajats98 I can complete it. Can I work on it.

**Comment by abhishekgupta368** [comment]
already commented and completed my task, can you assign me

**Comment by Adyasha8105** [comment]
Can you assign this task to me?

**Comment by rajats98** [comment]
@abhishekgupta368 assigning it to you, More issues to come don't panic guys!!
