### ISSUE TITLE
Adding a back button to return to the previous state of the page.

### ISSUE THREAD

**Issue by aashimgarg** [CropAi/Frontend#283]
- **I'm submitting a ...**

  - [ ] bug report
  - [x] feature request

- **Do you want to request a feature or report a bug?**
As after going on the upload an image there is no button to go to the previous page in case you do not want to upload an image.

**Comment by rajats98** [comment]
You can use the browser back button to return to the home, or you can use the logo!

**Comment by rajats98** [comment]
Though there is option of browser back, we can add.
Add on both analyze and result!.. 
make pr on dev branch!
check its position/size on each screen size

**Comment by rajats98** [comment]
@aashimgarg Update?

**Comment by aashimgarg** [comment]
> @aashimgarg Update?

working on it.

**Comment by rajats98** [comment]
@ashishnagpal2498  progress? Do you need more time?

**Comment by Nehank1709** [comment]
I would like to work on this. Is this issue still open? @rajats98

**Comment by rajats98** [comment]
@Nehank1709 this issue is almost resolved! 
You can't work on this now.
