### ISSUE TITLE
Responsive Issue on LP-2

### ISSUE THREAD

**Issue by abhushanaj** [CropAi/Frontend#286]
**I'm submitting a ...**
-  [x] bug report

 **What is the current behavior?**
 Responsiveness Problem in general on lp2
-  `>=650px` and `<=700`  range when contents are side by side the image is not proportionate with content. (the text-content break out unevenly and illustration becomes very small)

- In `500` range when contents go column-wise, the image's bottom part gets hidden below the viewport since the condition is set up that that in styling. (Overflow:hidden)

- Navbar and logo are off-centered from the baseline. (almost on all screens)

- Also since no scrolling is present ( the script to add scroll efects on navbar is redundant? Or the page was meant to be scrollable?

 **What is the expected behavior?**
- The column layout should be like `400` range where everything is so nicely arranged and looks good!
- CSS fixes on the above-mentioned problem.

@rajats98 Sir if valid I would like to try it. Also, 2 days needed since exams are going on .😅

**Comment by rajats98** [comment]
@abhu-A-J Assigning this to you!
