### ISSUE TITLE
Create CONTRIBUTE.md

### ISSUE THREAD

**Issue by vipuldcoder** [CropAi/Frontend#3]
Is your feature request related to a problem? Please describe.
This is feature which help new contributor to understand how they can contribute project and how we can help this project more effect and do understand what this project really is and how we can get started. Let's get started with making this project more better 👍

Describe the solution you'd like
Build a Document CONTRIBUTE.md that help everyone to understand what this project is and how the collaborator get started with this and understand what the current project status and Where they need to take.

**Comment by rajats98** [comment]
Anybody interested in working on this?
Pick any generic CONTRIBUTE.md update it corresponding to our project.
Add Gssoc details(marking, labeling) and also tell about only Gssoc participants are allowed to work on this repo(may be in the beginning of file).

**Comment by Mansi145** [comment]
Seems interesting. Can I work on this issue?

**Comment by rajats98** [comment]
Sure, Assigning it you @Mansi145

**Comment by rajats98** [comment]
@Mansi145 Submit it by tomorrow!

**Comment by annu12340** [comment]
I would like to work on this
