### ISSUE TITLE
Fixing HTML validator issue in index.html

### ISSUE THREAD

**Issue by Castella1313** [CropAi/Frontend#303]
Aims to solve the HTML validator issue shown in w3c html validator in index.html 

Screenshots:
![Screenshot 2020-05-07 at 10 45 09 PM](https://user-images.githubusercontent.com/53293156/81324471-a5e54300-90b4-11ea-9dec-fb100f044b1b.png)
![Screenshot 2020-05-07 at 10 45 16 PM](https://user-images.githubusercontent.com/53293156/81324473-a7167000-90b4-11ea-9bc2-a0130da7e8bf.png)

**Comment by Castella1313** [comment]
Is this a valid issue?

**Comment by rajats98** [comment]
Yes @Castella1313, you can work on it! 
Make sure while correcting these the design is preserved.

**Comment by Castella1313** [comment]
Sure, thanks!!!
