### ISSUE TITLE
Check Actions (greeting and label)

### ISSUE THREAD

**Issue by rajats98** [CropAi/Frontend#306]
Check labeler and greeting on Pull requests
Try to correct/change them if some error is there, otherwise remove!
(I think greeting label will not work for users other than member of this repo, so remove it)
In case any app needs to be configured, inform!

**Comment by shreyakapoor08** [comment]
can I

**Comment by shwetagurnani** [comment]
I can work on it

**Comment by rajats98** [comment]
@shreyakapoor08 assigning this to you!
