### ISSUE TITLE
PR template

### ISSUE THREAD

**Issue by kichloo** [CropAi/Frontend#32]
The PR template helps the reviewer to go through the changes made by the contributor rather than going through lines of codes to find it. I can design a PR template according to the structure of CropAi project. It can have Easy/ Medium as the Labels.

**Comment by kichloo** [comment]
@rajats98 Can I work on it?

**Comment by darkmatter18** [comment]
@kichloo can I work on it?

**Comment by rajats98** [comment]
@kichloo assigning it to you
