### ISSUE TITLE
Add jQuery to both landing pages

### ISSUE THREAD

**Issue by Sulekhiya** [CropAi/Frontend#35]
src/landing pages/ landing-2 and landing-3 
Add jQuery in both html files above the bootstrap script tag.
<script src="https://code.jquery.com/jquery-3.4.1.min.js" integrity="sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo=" crossorigin="anonymous"></script>

**Comment by abhushanaj** [comment]
@Sulekhiya Sir May I do this??

**Comment by Sapna2001** [comment]
Can I work on this?

**Comment by rajats98** [comment]
@abhu-A-J assign this to you
