### ISSUE TITLE
Add content in landing page 2

### ISSUE THREAD

**Issue by Sulekhiya** [CropAi/Frontend#36]
Add heading and button in landing-page2
(/src/landing pages/landing-page-2/landing2.html)
Remember, do not alter the background and button should be dummy.
Make sure the page remains not scrollable.

--refer landing page in Web Designs/design-2/

**Comment by Adyasha8105** [comment]
I want to work on this issue

**Comment by rajats98** [comment]
@Adyasha8105 Assigning this to you!
