### ISSUE TITLE
Create Web design(UI design) 

### ISSUE THREAD

**Issue by rajats98** [CropAi/Frontend#4]
### Create UI design in any _designing_ software (no restrictions on software, can be online/offline)

We need 1-3 pages i.e.

- [x] **Landing/Cover Page**
          Depends on your creativity, you can add a description, animation, or anything you feel 
          relevant

- [x] **Input form**
          This form contains only one required input field, that takes an image of leaf as input.
          
- [x] **Result**
         Here the result presented under 3 categories, namely,  Symptoms, Treatment, and 
         Recommended products.

1. One can work on one or more than one the these.
2. Cover page is optional.
3. Whole thing/flow can be shown on one or more pages.

**Add all the pictures/animations/icons or their link with your PR.** 
Submit in a proper format, so that UI developers can use it without having the designing tool.

This task is open to the creativity of the contributor.

Refer these: 
https://medium.theuxblog.com/11-best-prototyping-tools-for-ui-ux-designers-how-to-choose-the-right-one-c5dc69720c47
https://www.creativebloq.com/how-to/20-best-ui-design-tools

**Comment by abhushanaj** [comment]
@rajats98 Sir May I try this? I want to do the landing page.

**Comment by rajats98** [comment]
Yes, I am assigning it to you.

If anyone else also want to work on whole or on other parts may comment.It be will assigned to them also.

**Comment by goyalmuskan** [comment]
Sir, may I try this as well? @rajats98

**Comment by rajats98** [comment]
@goyalmuskan Sure, assigning this to you too, please reply on which parts you are going to work( input/result or whole) before starting.

Submit it by tomorrow evening, or latest by night.

**Comment by rajats98** [comment]
@abhu-A-J Are you still working on this, if you are please submit it by today.

**Comment by abhushanaj** [comment]
Yes Sir, I am but can I submit by tomorrow morning? I'll try to submit by tonight as first priority definitely

**Comment by rajats98** [comment]
Great @abhu-A-J

**Comment by Adyasha8105** [comment]
@rajats98 Please Sir, Can I try this?

**Comment by rajats98** [comment]
@Adyasha8105, Yes I am assigning it you also, Please mention on what parts(great if all) do you want to work.
And start working if you think you can submit it by tomorrow.

**Comment by goyalmuskan** [comment]
@rajats98 The landing page

**Comment by rajats98** [comment]
@goyalmuskan make a PR with relevant images/screenshot and resources, under Web designs directory design 2, or design 3 folder, which is available). You may refer #9, #10 , #11. 
If there is any confusion or issue, please let me know!

**Comment by rajats98** [comment]
@goyalmuskan @Adyasha8105 Submit your work tonight(or tomorrow till 8-9 AM).
