### ISSUE TITLE
directory structure, current logo and correcting readme

### ISSUE THREAD

**Issue by rajats98** [CropAi/Frontend#40]
- [x] Create a new folder in root directory named **designs**
- [x] Move Web Designs and logo-design to **designs**
- [x] in logo-designs create a folder submitted-logos
- [x] move all logos(except gssoc) into submitted-logos
- [x] Now copy logo logodesign-2.png to logo-designs and rename logo cropAi-logo.png
- [x] Update logo source in README.md

folder structure should look like this:
```
design
      Web Designs     _(contents remain same)_
      logo-designs
            submitted-logos
                  --logodesign-1.png
                  --logodesign-2.png
            --corpAi-logo.png      (copy of logodesign-2)
            --gssoc-logo.png
```

**Comment by abhushanaj** [comment]
Can I do this??
Also can you explain a little more what do you mean by update logo directory in readme.??

**Comment by rajats98** [comment]
yes, In readme we there is image(1st image) of logo, so update its source to new source (corpAi-logo)
If there is any doubt you can ask
Assigning this to you

**Comment by abhushanaj** [comment]
> yes, In readme we there is image(1st image) of logo, so update its source to new source (corpAi-logo)
> If there is any doubt you can ask
> Assigning this to you

Yes more doubt
Should I use github image links on readme or just make reference to image internally on readme??

**Comment by rajats98** [comment]
refer internally
