### ISSUE TITLE
Add content to index

### ISSUE THREAD

**Issue by rajats98** [CropAi/Frontend#47]
Update **src/index.html**
refer designs/Web Designs/design-1/landing-page

**Add both the buttons and heading, the _buttons should be dummy._
Add these content inside `div#landing_container`**
### We do not need any navbar or any link (as in design).
you might need to change the code written before, change it but make sure it almost looks same as design.

**Comment by abhishekgupta368** [comment]
I want to do it

**Comment by abhu-A-J** [comment]
@rajats98 Sir May I do this task?? Thank you!!

**Comment by Adyasha8105** [comment]
i want to work on this

**Comment by rajats98** [comment]
@abhishekgupta368 Assigning this to you

**Comment by abhishekgupta368** [comment]
thanks

**Comment by rajats98** [comment]
@abhishekgupta368 make sure that you structure your code keeping in mind that form_container and result_container divs will have content. (and only one div will be shown at time either landing or form or result)

**Comment by abhishekgupta368** [comment]
I need to design this part only, I am right?

![Capture](https://user-images.githubusercontent.com/39022530/78336371-e11fbe00-75ac-11ea-8482-8d12232f8504.PNG)

**Comment by rajats98** [comment]
> I need to design this part only, I am right?
> 
> ![Capture](https://user-images.githubusercontent.com/39022530/78336371-e11fbe00-75ac-11ea-8482-8d12232f8504.PNG)

yes, add actual buttons which do nothing
