### ISSUE TITLE
update landing page 3

### ISSUE THREAD

**Issue by rajats98** [CropAi/Frontend#48]
Change the href to # for Corp Ai anchor tag in navbar.
Find and Change the tree in the bg to a similar tree(of bigger size), so that it looks clear.

**Comment by abhushanaj** [comment]
@rajats98 Sir May I do this task?? Thank you!!
**EDIT:** Okay you can assign Satyam Sir. I'll take new one. He didnt work on any issues before on this REPO . Thanks!!

**Comment by Satyam3976** [comment]
Sir, Please assign me this  task, I want to work on this
EDIT: Ya, I am new to this Repo, Thank you @abhu-A-J

**Comment by Adyasha8105** [comment]
@rajats98 may i

**Comment by Adyasha8105** [comment]
> @rajats98 may I please as I have work on it already.

**Comment by rajats98** [comment]
@abhu-A-J That's very kind of you!! **#Sportsmanship**

**Comment by Adyasha8105** [comment]
@rajats98 that's why I delete my comment.

> @rajats98 Sir May I do this task?? Thank you!!
> **EDIT:** Okay you can assign Satyam Sir. I'll take new one. He didnt work on any issues before on this REPO . Thanks!!

**Comment by Satyam3976** [comment]
@Adyasha8105 Thanks to you too.

**Comment by rajats98** [comment]
> @rajats98 that's why I delete my comment.
> 
> > @rajats98 Sir May I do this task?? Thank you!!
> > **EDIT:** Okay you can assign Satyam Sir. I'll take new one. He didnt work on any issues before on this REPO . Thanks!!

Great!!

**Comment by rajats98** [comment]
@Satyam3976 Submit this by tonight, If there is an issue, ask!

**Comment by Adyasha8105** [comment]
@Satyam3976 If you are not working on this issue, Can I take it?

**Comment by Satyam3976** [comment]
Sorry for the delay, I had designed the tree in photoshop, please have a look at it @rajats98
