### ISSUE TITLE
Update README.md

### ISSUE THREAD

**Issue by rajats98** [CropAi/Frontend#5]
Add a brief introduction and working of application. Write basic working, it will be properly updated later on with screenshots. 

Add links to backend and data-modeling repos (give overview of each repo, if possible).

Also mention about Gssoc in the intro or separately.

Refer to #4 to get some idea.

**Comment by Sapna2001** [comment]
Will the resources be provided to write the working of the application, etc.

**Comment by rajats98** [comment]
@Sapna2001, for now just write about input and output. (see #4 for input and result)

**Comment by Sapna2001** [comment]
I would like to work on this issue. Please assign me this issue

**Comment by rajats98** [comment]
@Sapna2001 ,Assigned this issue to you.
