### ISSUE TITLE
About button functionality

### ISSUE THREAD

**Issue by rajats98** [CropAi/Frontend#52]
**index.html**
On clicking about show brief of project/application on right side (or wherever you like, but be sane :p), it should look good and the user must get a good experience,
**Do not remove the button while showing this, size or position may be changed (but avoid change of position/size)**  

You may show this _"CorpAi is a crop advisory app for farmers and gardeners. It can diagnose pest damage, plant disease and nutrient deficiencies that are affecting crops and can offer corresponding treatment measures."_

Any modification should be done inside **div with id=landing_container**

**Comment by abhu-A-J** [comment]
@rajats98 Sir May I do this task?? Thank you!!

**Comment by annu12340** [comment]
I would like to work on this

**Comment by priyalbhatewara123** [comment]
sir,i can work on this issue,haven't started contributing yet. Please assign this to me so that i can start with this.

**Comment by annu12340** [comment]
On which file should these modification be made

**Comment by rajats98** [comment]
@annu12340 index.html, Also edited in description now

**Comment by rajats98** [comment]
@annu12340 assigning this to you

**Comment by rajats98** [comment]
**PLEASE DON'T CHANGE CODE OUTSIDE THE Required DIV**, many people are working on this file simultaneously, 
you may update index.css, index.js inside assets

**Comment by rajats98** [comment]
@annu12340 Submit this by tonight, If there is a doubt or issue, you can ask!
