### ISSUE TITLE
Create input form

### ISSUE THREAD

**Issue by rajats98** [CropAi/Frontend#53]
**index.html**

**Add a form with single input(file input)** inside div with id=input_container

NOTE: while working add hidden class to div with id=landing_container and result_container

_while submitting add hidden class to input_container and result container_

If there is any confusion, kindly ask : ).

**Comment by abhishekgupta368** [comment]
I can do it

**Comment by abhishekgupta368** [comment]
any medium level coming

**Comment by shwetagurnani** [comment]
I am new to this project.I would like to work on this task,kindly assign it to me:).

**Comment by annu12340** [comment]
I would like to work on this

**Comment by Adyasha8105** [comment]
Sir, please assign this to me

**Comment by rajats98** [comment]
> I can do it

@abhishekgupta368  Assigned you a different issue : )
@shwetagurnani assigning this to you
**PLEASE DON'T CHANGE CODE OUTSIDE THE Required DIV**, many people are working on this file simultaneously.
you may update index.css, index.js inside assets

**Comment by rajats98** [comment]
@shwetagurnani make sure the page remains un-scrollable.

**Comment by rajats98** [comment]
@shwetagurnani Submit this by tonight!  If there is a doubt or issue, you can ask!

**Comment by abhushanaj** [comment]
@rajats98 Sir Is this open to take now!!?? I'd like to work on it, if it's open! Thanks!!

**Comment by Adyasha8105** [comment]
> Sir, please assign this to me

@rajats98 Sir, I also want to work on this issue.

**Comment by rajats98** [comment]
**@shwetagurnani please submit it by 4pm today**, otherwise this issue will be assigned to @Adyasha8105.

If you are stuck somewhere, or there is any doubt, please let me know!

**Comment by shwetagurnani** [comment]
Please review and let me know if any changes are to be done:)

**Comment by rajats98** [comment]
@Adyasha8105 Assigning this issue to you, As Shweta will not be able to complete it today.
you may check PR created by her and use her code if you want, and proceed according to reviews
or you may start from the beginning. Try to submit it ASAP.

**Comment by rajats98** [comment]
@Adyasha8105 read all the instructions carefully, and reviews on PR created Shewta before starting.

**Comment by Adyasha8105** [comment]
> @Adyasha8105 Assigning this issue to you, As Shweta will not be able to complete it today.
> you may check PR created by her and use her code if you want, and proceed according to reviews
> or you may start from the beginning. Try to submit it ASAP.

okay sir@rajats98
