### ISSUE TITLE
Update result div in index.html

### ISSUE THREAD

**Issue by rajats98** [CropAi/Frontend#54]
**index.html**
You need to show the following data inside the div(id=result_container), Don't make table with 3 columns as made in any of the designs.
**Show some creativity** 
ONLY MAKE CHANGES IN div#result_container
NOTE: while working add hidden class to div with id=landing_container and input_container
_while submitting add hidden class to input_container and result container_
If there is any confusion, kindly ask : ).

For now hard code this data

Disease Name: Pepper__bell___Bacterial_spot
Symptoms : 
1 : Leaf spots that appear on the lower surface of older leaves as small, pimples and on the upper leaf surface as small water-soaked spots are a symptom of bacterial spot.
2 : Eventually, the spots develop gray to tan centers with darker borders. Lesions enlarge during warm, humid weather. Leaves may then turn yellow, then brown and drop. Lesions may also develop on stems.
3:  Lesions may also develop on stems. Fruits develop small, raised rough spots that do not affect eating quality. Severely infected leaves will drop resulting in

Treatment :
1 : Treat seeds by soaking them for 2 minutes in a 10% chlorine bleach solution (1 part bleach; 9 parts water). Thoroughly rinse seeds and dry them before planting.
2 : Mulch plants deeply with a thick organic material like newspaper covered with straw or grass clippings.               
3 : Spray every 10-14 days with fixed copper (organic fungicide) to slow down the spread of infection.
4: Rotate peppers to a different location if infections are severe and cover the soil with black plastic mulch or black landscape fabric prior to planting.                         
                      
             
Recommended products :
1 : Neem Oil : https://www.planetnatural.com/product/organic-neem-oil/
2 : Garden Dust : https://www.planetnatural.com/product/garden-dust/

**Comment by abhishekgupta368** [comment]
I will do it.

**Comment by annu12340** [comment]
I would like to work on this

**Comment by annu12340** [comment]
I would like to work on this. Please assign it to me

**Comment by abhishekgupta368** [comment]
can you allote me, please?

**Comment by shwetagurnani** [comment]
Please assign this issue to me

**Comment by Adyasha8105** [comment]
please assign me????

**Comment by rajats98** [comment]
@abhishekgupta368 Assigning this to you, 
**PLEASE DON'T CHANGE CODE OUTSIDE THE Required DIV**, many people are working on this file simultaneously.
you may update index.css, index.js

**Comment by abhishekgupta368** [comment]
thanks

**Comment by rajats98** [comment]
@abhishekgupta368 make sure page remains un-scrollable if there is an issue/confusion for design you can ask.

**Comment by abhishekgupta368** [comment]
I was busy, Now, I will complete it.

**Comment by rajats98** [comment]
@abhishekgupta368  Submit this by tonight!  If there is a doubt or issue, you can ask!
