### ISSUE TITLE
Analyze button functionality 

### ISSUE THREAD

**Issue by rajats98** [CropAi/Frontend#55]
**Index.html**
NOTE: hidden class is already present in assests/index.css
1. Add 'hidden' class to div#input_container, div#result_container

1. make 3 functions in assets/index.js
       ```
         show_landing_container()
         show_input_container()
         show_result_container()
       ```
each function should add hidden class to other two div, and remove from the div to be shown, eg ,if          show_input_container() is called remove the hidden class from #input_container and add it to landing_container and result_container
(you can use jQuery, or plain js, it is not necessary to use hidden class method, you may use jQuery/js functions)
1. On click Analyze call show_input_container()

In case of any doubts ask : ).

**Comment by abhishekgupta368** [comment]
I can do it

**Comment by abhushanaj** [comment]
Can I do this??

**Comment by rajats98** [comment]
> I can do it

No doubt @abhishekgupta368, But assigned you a different issue, we need to work done parallelly

so Assigning it to you @abhu-A-J

**Comment by abhushanaj** [comment]
@rajats98 Sir, I need to change some previously written code because of the way it is styled. The entire body is given blue color and the landing page is inside the background, which should be other way around!!!

Also since absolute positioning is used on bottom images to keep them ar bottom:0 it will always stay at bottom since the relative parent is body directly so all other divs will go inside the landing div itself something like this!!!! 

Some Content are contents for the two remaining divs!!

What should I do?? Neep you help on this!!


![Screenshot (71)](https://user-images.githubusercontent.com/49617450/78368522-64f39d80-75e1-11ea-9ed9-490be9b085ec.png)

**Comment by rajats98** [comment]
Background for all of the divs is same, that's why it is outside. I understand the code might not be up to mark, but at this stage, I could not allow you to change to make changes, as it may affect 3-4 other participants.
And the image should be present always at the bottom.
And one more thing make updates such that page remains un-scrollable.
You may use any value of the position property of CSS (absolute/fixed...etc)

**Comment by rajats98** [comment]
> @rajats98 Sir, I need to change some previously written code because of the way it is styled. The entire body is given blue color and the landing page is inside the background, which should be other way around!!!
> 
> Also since absolute positioning is used on bottom images to keep them ar bottom:0 it will always stay at bottom since the relative parent is body directly so all other divs will go inside the landing div itself something like this!!!!
> 
> Some Content are contents for the two remaining divs!!
> 
> What should I do?? Neep you help on this!!
> 
> ![Screenshot (71)](https://user-images.githubusercontent.com/49617450/78368522-64f39d80-75e1-11ea-9ed9-490be9b085ec.png)

Hey, you are working on analyze button then why do you need to add content? 
I thought you are working on about button, although thanks for informing

**Comment by abhushanaj** [comment]
@rajats98 Sir Understood! So what I need to achieve is that CROP AI content should be replaced with other contents as per toggle feature!! ??  And all other things should remain as it it (logo,plants etc etc) ?? 
Is that correct?

**Comment by rajats98** [comment]
Yes, we just need to show one 3 divs at one time.
You need to 3 functions (2 will be used in future)
and 1 which will be used now, will hide the landing_container and show the input_container. (half toggle, as analysis button, will only be shown in landing_container, and it will always be used to hide  landing_container and show input_container )

**Comment by abhishekgupta368** [comment]
> 
> 
> @rajats98 Sir, I need to change some previously written code because of the way it is styled. The entire body is given blue color and the landing page is inside the background, which should be other way around!!!
> 
> Also since absolute positioning is used on bottom images to keep them ar bottom:0 it will always stay at bottom since the relative parent is body directly so all other divs will go inside the landing div itself something like this!!!!
> 
> Some Content are contents for the two remaining divs!!
> 
> What should I do?? Neep you help on this!!
> 
> ![Screenshot (71)](https://user-images.githubusercontent.com/49617450/78368522-64f39d80-75e1-11ea-9ed9-490be9b085ec.png)

acconding to UI, I was told to make it bottom

**Comment by abhishekgupta368** [comment]
can please specify where is my code giving wrong output and if you try o zoom it, the image will also scale, can you please tell me, which website doesn't scale on zoom @abhu-A-J

**Comment by rajats98** [comment]
@abhishekgupta368 No worries, No blames, No criticism, No fights!!  In case if there is some problem we will update, and step forward.
I merged your PR after checking, do not take it on you.

**Comment by abhishekgupta368** [comment]
you are telling that styling is wrong, just highlight it.
I want feedback for my code.

**Comment by rajats98** [comment]
> you are telling that styling is wrong, just highlight it.
> I want feedback for my code.

If I felt like that I would have given a review, It is just that everyone have a different way of organizing things and different style of writing code. Your code is perfectly alright !!

**Comment by abhishekgupta368** [comment]
These images are different level scaling:

![cap1](https://user-images.githubusercontent.com/39022530/78375652-c10eef80-75ea-11ea-827b-83ff891f7f3b.PNG)
![ap3](https://user-images.githubusercontent.com/39022530/78375655-c1a78600-75ea-11ea-9915-755facf22ce4.PNG)
![cap4](https://user-images.githubusercontent.com/39022530/78375656-c2401c80-75ea-11ea-8852-9596870dde27.PNG)
![cap2](https://user-images.githubusercontent.com/39022530/78375660-c3714980-75ea-11ea-8943-e802bf75bccf.png)

**Comment by abhushanaj** [comment]
> can please specify where is my code giving wrong output and if you try o zoom it, the image will also scale, can you please tell me, which website doesn't scale on zoom @abhu-A-J

Areh no no! I said the styling is wrong because the entire body had the color and background set. 

I thought we have to make three different sections and style them different with different background! So that's why I asked the permission to change. But it was my fault , K misunderstood the concept and Sir cleared it right above! Sorry if I made you think you work was wrong! It was a mistake from my end not yours!!

**Comment by abhishekgupta368** [comment]
These small mistakes can lead to a big bug. please take care about.

**Comment by abhushanaj** [comment]
> > you are telling that styling is wrong, just highlight it.
> > I want feedback for my code.
> 
> If I felt like that I would have given a review, It is just that everyone have a different way of organizing things and different style of writing code. Your code is perfectly alright !!



> @abhishekgupta368 No worries, No blames, No criticism, No fights!! In case if there is some problem we will update, and step forward.
> I merged your PR after checking, do not take it on you.

Yes yes, the mistake was mine misunderstanding things. It's my fault only. Sorry about thr confusion. Didn't mean to do that! I hope everything is cleared?
