### ISSUE TITLE
Design a Webpage for contributors

### ISSUE THREAD

**Issue by rajats98** [CropAi/Frontend#57]
Design the webpage using any designing software
It should have two parts 
1. Admin and Mentors
1. Participants

Add shape(maybe rectangle) containing an image(profile), Name, and role(Admin, mentor or participant)

It will be assigned to 5 participants, each participant must only submit one design, if you have more than one ideas, design and submit the best one.

Deadline 7th April 

EDIT: 
1. make folder named designs/Web Designs/contributors
1. Submit your design inside contributors, name your folders contributors-x (x=1,2...)
1. Add proper resources(any graphics used, that you think will be required while translating the design to code) with your design
1. Add dummy data, some images should be left blank and there should be proper design for empty image!
1. Add suitable number of cards/user-data that fully define your design

**Comment by Adyasha8105** [comment]
Can I do this??

**Comment by abhushanaj** [comment]
Is is open for to take for ppl who are already assigned??

**Comment by rajats98** [comment]
> Is is open for to take for ppl who are already assigned??

yes, do previous issues asap, this can be submitted till 7th of this month.
@abhu-A-J Do you want to work?

**Comment by rajats98** [comment]
@Adyasha8105 assigning this to you

**Comment by Satyam3976** [comment]
@rajats98 Sir, Please issue me this task, I also want to work on this.

**Comment by abhushanaj** [comment]
> > Is is open for to take for ppl who are already assigned??
> 
> yes, do previous issues asap, this can be submitted till 7th of this month.
> @abhu-A-J Do you want to work?

Yes!!!

**Comment by rajats98** [comment]
> @rajats98 Sir, Please issue me this task, I also want to work on this.

@Satyam3976 Assigning this to you also

**Comment by shwetagurnani** [comment]
Sir, I am also interested in working on this issue

**Comment by rajats98** [comment]
@abhu-A-J, @shwetagurnani assigning this to you both

**Comment by rajats98** [comment]
@Adyasha8105 @abhu-A-J @shwetagurnani @Satyam3976
I have updated instructions go through them

**Comment by annu12340** [comment]
I am also a front end dev. I would also like to work on this issue

**Comment by rajats98** [comment]
@annu12340 Assigning this to you,
You have to only design it, no code :) !!
read instructions

**Comment by annu12340** [comment]
👍
