### ISSUE TITLE
Issue template

### ISSUE THREAD

**Issue by kichloo** [CropAi/Frontend#58]
The issue template helps the contributor to briefly mention the issue and the change required to fix it. I can design a issue template according to the structure of CropAi project. It can have Easy/ Medium as the Labels.

**Comment by rajats98** [comment]
We do not require an issue template now as most of the issues are raised by mentors, will re-open the issue later if needed

**Comment by rajats98** [comment]
@kichloo Do you want to work on this?

**Comment by Adyasha8105** [comment]
@rajats98 Can I as it is necessary now?

**Comment by kichloo** [comment]
@rajats98 Yes I would like to take it up!

**Comment by rajats98** [comment]
Add it to docs 
name it similar to pull request template present there

@kichloo assigning to you!

**Comment by kichloo** [comment]
@rajats98 Can you make the label as Easy as the PR template was also easy

**Comment by rajats98** [comment]
Nopes! It would be considered beginner
