### ISSUE TITLE
Update Documentation

### ISSUE THREAD

**Issue by rajats98** [CropAi/Frontend#61]
- [x] Move vision, from CONTRIBUTE.md to README (below INTRO)

- [x] Update Project Admin and Mentors, Slack Channel from CONTRIBUTE.md (i.e. name with github link)

- [x] Remove owners, mentors, slack channel from CONTRIBUTE.md

- [x] Move Our Pledge, Our Standards, Our Responsibilities, Scope, Enforcement, Attribution from CONTRIBUTE.md to CODE_OF_CONDUCT.md (create new file).

Please don't comment if you are working on any issue(except #1, #57)

**Comment by abhu-A-J** [comment]
Can I??

**Comment by Adyasha8105** [comment]
can i??

**Comment by Adyasha8105** [comment]
> Can I??

@abhu-A-J very fast...

**Comment by rajats98** [comment]
yes @abhu-A-J , Assigning it to you

**Comment by Adyasha8105** [comment]
> yes @abhu-A-J , Assigning it to you

@abhu-A-J @rajats98  he has done a lot many tasks

**Comment by abhushanaj** [comment]
> > yes @abhu-A-J , Assigning it to you
> 
> @abhu-A-J @rajats98 he has done a lot many tasks

@rajats98 Can you assign @Adyasha8105? . She always misses it by seconds! Thank you

**Comment by rajats98** [comment]
@Adyasha8105 assigning it to you, 
@abhu-A-J Great, :+1: :100:, **#sportsmanship**

**Comment by rajats98** [comment]
@Adyasha8105 show some gratitude :sweat_smile: :laughing:

**Comment by Adyasha8105** [comment]
> @Adyasha8105 show some gratitude 😅 😆

Ya, already done through slack messages.
Ok once again @abhu-A-J Thank you so much.

**Comment by abhushanaj** [comment]
> > @Adyasha8105 show some gratitude 😅 😆
> 
> Ya, already done through slack messages.
> Ok once again @abhu-A-J Thank you so much.

Welcome  , by the way you missed by literally seconds on this one!!! You would have got this, if I would'nt have been active !! 🤣.

**Comment by Adyasha8105** [comment]
> > > @Adyasha8105 show some gratitude 😅 😆
> > 
> > 
> > Ya, already done through slack messages.
> > Ok once again @abhu-A-J Thank you so much.
> 
> Welcome, by the way, you missed by literally seconds on this one!!! You would have got this if I wouldn't have been active !! 🤣.

I think you are active all the time😆.
