### ISSUE TITLE
Update Docs 

### ISSUE THREAD

**Issue by rajats98** [CropAi/Frontend#64]
Create a docs folder and move all .md files inside it

and update the files as follows 
**PR_template.md**
rename to pull_request_template.md
add a comment in Fixes issue, "Use one of fixes or addresses and remove the other one"

**README.md**
Remove How to start contributing section

Inside Important Notice add this line and add relative links to both files 
Before contributing to this project do check CONTRIBUTING.md file and CODE_OF_CONDUCT.md file.

### **UPDATE ANY RELATIVE LINK(image,file) THAT GETS AFFECTED BY MOVING FILES TO NEW DIRECTORY**

In case of any doubt,ask!

**Comment by rajats98** [comment]
Please don't comment if you are working on any issue(except #1, #57)

**Comment by Adyasha8105** [comment]
I want to work on this issue

**Comment by rajats98** [comment]
@Adyasha8105 assigning this to you
