### ISSUE TITLE
Show input image

### ISSUE THREAD

**Issue by rajats98** [CropAi/Frontend#79]
inside input_container
		show input image on the form( at place of dummy image icon)

**At one time only one of the div will be shown (landing_container/ input_container/ result_container).**

**Comment by abhushanaj** [comment]
@rajats98 Sir May I do this task?? Thank you!!
Also this is for which page?

**Comment by Adyasha8105** [comment]
@rajats98  Can i?

**Comment by rajats98** [comment]
> @rajats98 Sir May I do this task?? Thank you!!
> Also this is for which page?

index.html

**Comment by rajats98** [comment]
any more doubts are welcome :)
