### ISSUE TITLE
Submit form functionality

### ISSUE THREAD

**Issue by rajats98** [CropAi/Frontend#80]
On submitting form
   create a new js function() with following functionality

       stop default action of form.
       store input_image in a variable

	   
	   create a js variable as 
	   analysis_report_json = {
	   Disease: "Pepper Bell Healthy",
	   Symptoms: {
	      "1":
	        "Initial symptoms of infection are the formation of small, circular, water-soaked spots on leaves, stems, petioles and/or peduncles",
	      "2":
	        "Infected Pepper Bell have Circular lesions on fruit which contain tan to orange to black concentric rings in the center.",
	      "3":
	        "It can have lesions may also occur on leaves and stems and appear as irregularly shaped gray spots with dark margins",
	      "4":
	        "Seeds did not germinate; seedlings collapsing and dying; dark stems which are shriveled near the soil line",
	      "5": " Water-soaked lesions on the stem and discolored roots.",
	      "6":
	        "High numbers of lesions may form on leaves causing them to turn yellow and drop from the plant."
	    },
	    Treatment: {
	      "1":
	        "Plant only diseasefree, certified seed",
	      "2":
	        "Always plant disease-free seeds and transplants.",
	      "3":
	        "Seeds can be freed from infection by treating with hot water.",
	      "4":
	        "Use disease free planting material; remove and destroy all crop debris after harvest, or plow material deeply under soil",
	      "5":"Magnesium deficiency can be prevented by applying dolomite lime to the soil, if an increase in soil pH is required, or through applications of a fertilizer containing magnesium."
	    },
	    Recommended_Product: {
	      "1": "Chlorothalonil-720-SFT : https://www.amazon.com/Chlorothalonil-Generic-Daconil-weatherstik-quali-1060/dp/B004GTOKSO",
	      "2": " Tafgor-Dimethoate : https://www.amazon.in/Tata-TATA-Tafgor-Dimethoate-Insecticide/dp/B074CCXPKF",
	      "3": "Ethion Insecticide : https://www.indiamart.com/proddetail/ethion-insecticide-12777127212.html",
	      "4":"Vector Super : https://www.amazon.in/Vector-100ML-IMIDACLOPRID-Systemic-Insecticide/dp/B07D7YTYTB"
	    }
	   }

	   update the data in result_container using js, while writing code keep in mind the analysis_report_json will be differnt for differnt input( no. of points under any inner-obect may change), you may change html as required(like you may add id to suitable elements)

	   call show_result_container() 

   delete dummy data from result_container (keep the required structure)

**Comment by abhishekgupta368** [comment]
I can do it. assign me.

**Comment by abhu-A-J** [comment]
@rajats98 Sir May I do this task?? Thank you!!

**Comment by abhishekgupta368** [comment]
Assign me, I will do this.

**Comment by Adyasha8105** [comment]
Can I work on this issue ?

**Comment by annu12340** [comment]
I would like to work on this issue

**Comment by Satyam3976** [comment]
Can i work on this?

**Comment by rajats98** [comment]
@Adyasha8105 assigning this to you

**Comment by rajats98** [comment]
In case of any doubt, Kindly ask!! 
Naming should be meaningful, add comments to make code readable, and easy to understand.

**Comment by Adyasha8105** [comment]
@rajats98 Okay :)

**Comment by abhishekgupta368** [comment]
I have done my previous Issue, Can I do this?

**Comment by rajats98** [comment]
No, it is currently assigned to another participant
