### ISSUE TITLE
update Analyze button functionality

### ISSUE THREAD

**Issue by rajats98** [CropAi/Frontend#81]
create a new function which will called on clicking Analyze
function should do the following
```
append '?q=analyze' to url (do not redirect, use windows.pushState(), or any other method)
call show_input_container()
```

**Comment by abhishekgupta368** [comment]
I can do it.

**Comment by Adyasha8105** [comment]
@rajats98  Can I work on this?

**Comment by Satyam3976** [comment]
Please assign me this, I want to work on this

**Comment by rajats98** [comment]
@Satyam3976 assigning this to you

**Comment by rajats98** [comment]
In case of any doubt, Kindly ask!!
Naming should be meaningful, add comments to make code readable, and easy to understand.
