### ISSUE TITLE
Faking Routes

### ISSUE THREAD

**Issue by rajats98** [CropAi/Frontend#82]
on the load of the page check url
   www.domainname.com?q="section"
	 (eg. www.corp-ai.com?q=analyze)

	if section == analyze
		call show_input_container();
	if section == result
		redirect to '/'

**Comment by abhu-A-J** [comment]
@rajats98 Sir May I do this task?? Thank you!!

**Comment by annu12340** [comment]
I would like to work on this issue

**Comment by Adyasha8105** [comment]
@rajats98 May I?

**Comment by annu12340** [comment]
On which file, should I add this? Is it in the assets/index/js ?

**Comment by rajats98** [comment]
> On which file, should I add this? Is it in the assets/index/js ?

yes

**Comment by rajats98** [comment]
In case of any doubt, Kindly ask!!
Naming should be meaningful, add comments to make code readable, and easy to understand.

**Comment by annu12340** [comment]
Ok
