### ISSUE TITLE
Add link to logo

### ISSUE THREAD

**Issue by rajats98** [CropAi/Frontend#83]
on clicking logo, go to "/"

**Comment by abhishekgupta368** [comment]
I can do it.

**Comment by annu12340** [comment]
I would like to work on this issue

**Comment by Adyasha8105** [comment]
Can I work on this?

**Comment by rajats98** [comment]
@abhishekgupta368 assigning this to you, But next time make sure you do not comment dot to comment earlier and then edit, this is not once or twice noticing this for quite a while, This is not Fair. Otherwise, you may not be allowed to contribute further

**Comment by rajats98** [comment]
In case of any doubt, Kindly ask!!
Naming should be meaningful, add comments to make code readable, and easy to understand.
