### ISSUE TITLE
Input image mandatory and show img on result page also

### ISSUE THREAD

**Issue by rajats98** [CropAi/Frontend#90]
**index.html, index.js**

- [ ] form should not submit without input, give proper warning
- [ ] design input button 
- [ ] inside event listener for form submit, store image in a variable.

- [ ] pass that img variable to update_result function, add relevant parameter in function definiton
- [ ] inside update_result, add code that will update the image in result_container

**Comment by Adyasha8105** [comment]
can I?

**Comment by rajats98** [comment]
@Adyasha8105 assigned to you

**Comment by annu12340** [comment]
I would also like to work on this issue
