### ISSUE TITLE
Add GitHub actions to the project.

### ISSUE THREAD

**Issue by aashimgarg** [CropAi/Frontend#93]
I will add github actions to the project. GitHub Actions makes it easy to automate all your software workflows, now with world-class CI/CD.

Should i work with this as this will be very good for the project.

@rajats98 should i proceed with it.

About me:-
GSSoC Aspirant.

**Comment by aashimgarg** [comment]
Please assign me this issue.

**Comment by rajats98** [comment]
Actually, this project is divided into 4 repositories. so, I don't think currently we can properly set it up.
Closing the issue for now.
In case we require it in the future, I will definitely reopen only this issue

**Comment by rajats98** [comment]
@aashimgarg Assigning this to you!

**Comment by abhushanaj** [comment]
Open for collaborations? I can also provide some good ones here?

**Comment by rajats98** [comment]
@abhu-A-J let him start, then you can update if you feel like! :+1:

**Comment by rajats98** [comment]
@aashimgarg Are you working on this? Give me confirmation by the end of day!

**Comment by aashimgarg** [comment]
> @aashimgarg Are you working on this? Give me confirmation by the end of day!

yas.

**Comment by rajats98** [comment]
@aashimgarg do this by tomorrow!

**Comment by aashimgarg** [comment]
what are the github tokens that we can add?

**Comment by rajats98** [comment]
are you talking about repo-token ?

**Comment by aashimgarg** [comment]
i mean to say the github actions that we can add for the website.

**Comment by aashimgarg** [comment]
you can list those..

**Comment by rajats98** [comment]
just set up automations for greetings and labeler
the labeler should add only tag "gssoc20"!

**Comment by rajats98** [comment]
@aashimgarg when can I expect this?

**Comment by rajats98** [comment]
@abhu-A-J you can start working on issue tomorrow 10 am, if work is not updated!
