### ISSUE TITLE
Clear the results before appending result

### ISSUE THREAD

**Issue by rajats98** [CropAi/Frontend#99]
Index.html index.js

In result container before appending the result, clear the previous content.
Test your functionality by submitting input multiple times (use analyze other crop button below the results and submit the form again)

Understand current functionality before starting!

If there is any doubt, Kindly ask.
Code neatly, Comment nicely!!

**Comment by abhu-A-J** [comment]
@rajats98 Sir May I ??

**Comment by shwetagurnani** [comment]
pls assign me this issue

**Comment by abhishekgupta368** [comment]
I can do it.

**Comment by Adyasha8105** [comment]
Can I take this issue?

**Comment by Satyam3976** [comment]
Can I?

**Comment by rajats98** [comment]
@abhishekgupta368 assigning this to you

**Comment by rajats98** [comment]
@abhishekgupta368 
In case, after reading the description, you feel like you will not be able to do this,please let me know!

**Comment by annu12340** [comment]
Can I work on this issue
